#!/usr/bin/env bash
# Tests for deterministic, sanitized GitHub PR metadata generation.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

pass() { printf '✓ %s\n' "$1"; }
fail() { printf '✗ %s\n' "$1" >&2; exit 1; }

extract_function() {
  local name="$1"
  awk -v fn="$name" '
    $0 ~ "^" fn "\\(\\) \\{" { capture=1; depth=0 }
    capture {
      print
      for (i = 1; i <= length($0); i++) {
        ch = substr($0, i, 1)
        if (ch == "{") depth++
        if (ch == "}") depth--
      }
      if (capture && depth == 0) exit
    }
  ' "$ROOT_DIR/kaseki-agent.sh"
}

# Load only the helpers needed for PR metadata and the existing JSON encoding path.
eval "$(extract_function sanitize_pr_metadata_text)"
eval "$(extract_function truncate_pr_metadata_text)"
eval "$(extract_function derive_pr_title)"
eval "$(extract_function format_pr_command_results)"
eval "$(extract_function build_pr_body)"
eval "$(extract_function run_node_subprocess)"

mkdir -p /results "$TMP_DIR/results"
PRE_VALIDATION_TIMINGS_FILE="$TMP_DIR/results/pre-validation-timings.tsv"
VALIDATION_TIMINGS_FILE="$TMP_DIR/results/validation-timings.tsv"
cat > "$PRE_VALIDATION_TIMINGS_FILE" <<'TSV'
npm run check	0	3	tee_exit=0 filter_exit=0
TSV
cat > "$VALIDATION_TIMINGS_FILE" <<'TSV'
npm run test -- --token=abc123	0	12	tee_exit=0 filter_exit=0
npm run build	0	5	tee_exit=0 filter_exit=0
TSV

INSTANCE_NAME="kaseki-test-instance"
TASK_PROMPT='Fix OAuth flow for quoted "input" using secret=abc123 and ghp_1234567890abcdef; add regression tests.'
KASEKI_MODEL='openrouter/test-model'
ACTUAL_MODEL='openrouter/actual-model'
START_EPOCH=$(($(date +%s) - 125))
VALIDATION_EXIT=0
QUALITY_EXIT=0
SECRET_SCAN_EXIT=0
GIT_REF='main'
feature_branch='kaseki/kaseki-test-instance'

pr_title="$(derive_pr_title)"
pr_body="$(build_pr_body)"

case "$pr_title" in
  "Kaseki: OAuth flow"*) pass "PR title is derived from the task prompt" ;;
  *) fail "PR title was not derived from prompt: $pr_title" ;;
esac

if printf '%s\n%s' "$pr_title" "$pr_body" | grep -Eq 'secret=abc123|ghp_1234567890abcdef|--token=abc123'; then
  fail "PR metadata leaked secret-like values"
else
  pass "PR metadata redacts secret-like values"
fi

for expected in \
  '## Request summary' \
  '## Validation' \
  '### Pre-agent validation commands' \
  '### Post-agent validation commands' \
  'npm run check — exit 0, 3s' \
  'npm run test -- --[redacted] — exit 0, 12s' \
  '## Quality checks' \
  'Quality gate: passed' \
  'Secret scan: passed' \
  '## Run metadata' \
  'Model: requested openrouter/test-model; actual openrouter/actual-model' \
  'Duration: 125s' \
  'Generated by: Kaseki agent'; do
  if grep -Fq "$expected" <<<"$pr_body"; then
    pass "PR body contains: $expected"
  else
    fail "PR body missing expected text: $expected"
  fi
done

# Preserve the existing safe JSON encoding path used by the GitHub PR API payload.
run_node_subprocess pr_title_json "console.log(JSON.stringify(require('fs').readFileSync(0, 'utf8')))" "$pr_title" "$TMP_DIR/node.log"
run_node_subprocess pr_body_json "console.log(JSON.stringify(require('fs').readFileSync(0, 'utf8')))" "$pr_body" "$TMP_DIR/node.log"
payload="{\"title\": $pr_title_json, \"body\": $pr_body_json, \"head\": \"$feature_branch\", \"base\": \"$GIT_REF\", \"draft\": true}"

PAYLOAD="$payload" node <<'NODE'
const payload = JSON.parse(process.env.PAYLOAD);
if (!payload.title.startsWith('Kaseki: OAuth flow')) process.exit(1);
if (!payload.body.includes('## Request summary')) process.exit(2);
if (!payload.draft) process.exit(3);
NODE
pass "GitHub PR API payload JSON preserves generated title/body"
