#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034
# Tests validation-phase allowlist enforcement against before/after state snapshots.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

export KASEKI_WORKSPACE_DIR="$TMP_DIR"
export KASEKI_RESULTS_DIR="$TMP_DIR/results"

# shellcheck source=../scripts/allowlist-helper.sh
source "$ROOT_DIR/scripts/allowlist-helper.sh"
export API_KEY="test-api-key"
export VALIDATION_ENDPOINT=""

pass() { printf '✓ %s\n' "$1"; }
fail() { printf '✗ %s\n' "$1" >&2; exit 1; }

emit_event() {
  printf '%s' "$1" >> "$TMP_DIR/results/events.log"
  shift
  while [ "$#" -gt 0 ]; do
    printf ' %s' "$1" >> "$TMP_DIR/results/events.log"
    shift
  done
  printf '\n' >> "$TMP_DIR/results/events.log"
}

append_quality_violation() { :; }

# Load only the helpers under test, while redirecting their container-only
# absolute paths into this test's temporary workspace.
eval "$(awk '
  /^check_validation_allowlist\(\)/ { emit_check=1 }
  /^check_secret_scan_allowlist\(\)/ { emit_check=0 }
  emit_check { print }
  /^collect_changed_file_set\(\)/ { emit_collect=1 }
  /^restore_cleanup_disallowed_changes\(\)/ { emit_collect=0 }
  emit_collect { print }
' "$ROOT_DIR/kaseki-agent.sh" | sed "s#/workspace/repo#$TMP_DIR/repo#g; s#/results#$TMP_DIR/results#g")"

reset_quality_state() {
  QUALITY_EXIT=0
  QUALITY_FAILURE_REASON=""
  VALIDATION_ALLOWLIST_FAILURE_REASON=""
  : > "$TMP_DIR/results/quality.log"
  : > "$TMP_DIR/results/events.log"
  : > "$TMP_DIR/results/changed-files.txt"
  rm -f "$TMP_DIR/results/validation-before-state.txt" \
    "$TMP_DIR/results/validation-after-state.txt" \
    "$TMP_DIR/results/validation-changed-files.txt"
}

mkdir -p "$TMP_DIR/results" "$TMP_DIR/repo"
cd "$TMP_DIR/repo"
git init --initial-branch=main -q
git config user.email "test@kaseki.local"
git config user.name "Test User"
printf 'original\n' > tracked.txt
git add tracked.txt
git commit -q -m initial

# An existing agent change outside KASEKI_VALIDATION_ALLOWLIST should not fail
# when validation leaves its state untouched.
reset_quality_state
KASEKI_VALIDATION_ALLOWLIST='allowed/**'
printf 'agent change\n' > tracked.txt
collect_changed_file_state "$TMP_DIR/results/validation-before-state.txt"
collect_changed_file_state "$TMP_DIR/results/validation-after-state.txt"

if check_validation_allowlist; then
  pass 'validation allowlist ignores pre-existing agent changes when validation does not mutate them'
else
  fail 'validation allowlist should ignore untouched pre-existing agent changes outside the allowlist'
fi
[ "$QUALITY_EXIT" -eq 0 ] || fail "expected QUALITY_EXIT=0 for untouched agent change, got $QUALITY_EXIT"
[ ! -s "$TMP_DIR/results/validation-changed-files.txt" ] || fail 'no validation-mutated files should be recorded for untouched agent changes'

git restore --staged --worktree -- tracked.txt

# A new validation-generated file outside KASEKI_VALIDATION_ALLOWLIST should fail.
reset_quality_state
KASEKI_VALIDATION_ALLOWLIST='allowed/**'
collect_changed_file_state "$TMP_DIR/results/validation-before-state.txt"
printf 'generated by validation\n' > validation.log
collect_changed_file_state "$TMP_DIR/results/validation-after-state.txt"

if check_validation_allowlist; then
  fail 'validation allowlist should fail for a validation-generated file outside the allowlist'
else
  pass 'validation allowlist rejects validation-generated files outside the allowlist'
fi
[ "$QUALITY_EXIT" -eq 7 ] || fail "expected QUALITY_EXIT=7 for generated file, got $QUALITY_EXIT"
[ "$VALIDATION_ALLOWLIST_FAILURE_REASON" = "$QUALITY_FAILURE_REASON" ] || fail "validation allowlist reason should mirror quality failure reason"
printf '%s' "$VALIDATION_ALLOWLIST_FAILURE_REASON" | grep -Fq 'validation_allowlist_check: 1 file(s)' || fail 'expected dedicated validation allowlist failure reason'
grep -Fxq 'validation.log' "$TMP_DIR/results/validation-changed-files.txt" || fail 'validation-generated file should be recorded as validation-changed'
rm -f validation.log

# An already agent-changed file outside KASEKI_VALIDATION_ALLOWLIST should fail
# if validation mutates it again.
reset_quality_state
KASEKI_VALIDATION_ALLOWLIST='allowed/**'
printf 'agent change\n' > tracked.txt
collect_changed_file_state "$TMP_DIR/results/validation-before-state.txt"
printf 'validation mutation\n' > tracked.txt
collect_changed_file_state "$TMP_DIR/results/validation-after-state.txt"

if check_validation_allowlist; then
  fail 'validation allowlist should fail when validation mutates a pre-existing agent change outside the allowlist'
else
  pass 'validation allowlist rejects validation-mutated pre-existing agent changes outside the allowlist'
fi
[ "$QUALITY_EXIT" -eq 7 ] || fail "expected QUALITY_EXIT=7 for validation mutation, got $QUALITY_EXIT"
printf '%s' "$VALIDATION_ALLOWLIST_FAILURE_REASON" | grep -Fq 'validation_allowlist_check: 1 file(s)' || fail 'expected dedicated validation allowlist failure reason for validation mutation'
grep -Fxq 'tracked.txt' "$TMP_DIR/results/validation-changed-files.txt" || fail 'validation-mutated tracked file should be recorded as validation-changed'

printf '\n✅ validation allowlist state snapshot tests passed\n'
