#!/usr/bin/env bash

# Preserve the one-value compatibility override before configure_phase_budget
# starts exporting its active, phase-specific target.
if [ -z "${KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS_OVERRIDE+x}" ]; then
  KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS_OVERRIDE="${KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS:-}"
fi

configure_phase_budget() {
  local phase="$1" tool_output_override="${KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS_OVERRIDE:-}"
  case "$phase" in
    scouting)
      KASEKI_PHASE_MAX_CONTEXT_TOKENS="${KASEKI_SCOUTING_MAX_CONTEXT_TOKENS:-20000}"
      KASEKI_PHASE_MAX_TURNS="${KASEKI_SCOUTING_MAX_TURNS:-6}"
      KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS="${KASEKI_SCOUTING_MAX_TOOL_OUTPUT_TOKENS:-4000}"
      KASEKI_PHASE_OUTPUT_TOKEN_TARGET="${KASEKI_SCOUTING_MAX_OUTPUT_TOKENS:-2048}"
      ;;
    goal-setting)
      KASEKI_PHASE_MAX_CONTEXT_TOKENS="${KASEKI_GOAL_SETTING_MAX_CONTEXT_TOKENS:-18000}"
      KASEKI_PHASE_MAX_TURNS="${KASEKI_GOAL_SETTING_MAX_TURNS:-6}"
      KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS="${KASEKI_GOAL_SETTING_MAX_TOOL_OUTPUT_TOKENS:-4000}"
      KASEKI_PHASE_OUTPUT_TOKEN_TARGET="${KASEKI_GOAL_SETTING_MAX_OUTPUT_TOKENS:-2048}"
      ;;
    goal-check)
      KASEKI_PHASE_MAX_CONTEXT_TOKENS="${KASEKI_GOAL_CHECK_MAX_CONTEXT_TOKENS:-24000}"
      KASEKI_PHASE_MAX_TURNS="${KASEKI_GOAL_CHECK_MAX_TURNS:-6}"
      KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS="${KASEKI_GOAL_CHECK_MAX_TOOL_OUTPUT_TOKENS:-3000}"
      KASEKI_PHASE_OUTPUT_TOKEN_TARGET="${KASEKI_GOAL_CHECK_MAX_OUTPUT_TOKENS:-1536}"
      ;;
    run-evaluation)
      KASEKI_PHASE_MAX_CONTEXT_TOKENS="${KASEKI_RUN_EVALUATION_MAX_CONTEXT_TOKENS:-24000}"
      KASEKI_PHASE_MAX_TURNS="${KASEKI_RUN_EVALUATION_MAX_TURNS:-6}"
      KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS="${KASEKI_RUN_EVALUATION_MAX_TOOL_OUTPUT_TOKENS:-3000}"
      KASEKI_PHASE_OUTPUT_TOKEN_TARGET="${KASEKI_RUN_EVALUATION_MAX_OUTPUT_TOKENS:-1536}"
      ;;
    *)
      KASEKI_PHASE_MAX_CONTEXT_TOKENS="${KASEKI_CODING_MAX_CONTEXT_TOKENS:-32000}"
      KASEKI_PHASE_MAX_TURNS="${KASEKI_CODING_MAX_TURNS:-36}"
      KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS="${KASEKI_CODING_MAX_TOOL_OUTPUT_TOKENS:-8000}"
      KASEKI_PHASE_OUTPUT_TOKEN_TARGET="${KASEKI_CODING_OUTPUT_TOKEN_TARGET:-4096}"
      ;;
  esac

  if [[ "$tool_output_override" =~ ^[1-9][0-9]*$ ]]; then
    KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS="$tool_output_override"
  fi
  KASEKI_PHASE_BUDGET_ENFORCEMENT="soft_target"
  export KASEKI_PHASE_MAX_CONTEXT_TOKENS KASEKI_PHASE_MAX_TURNS
  export KASEKI_PHASE_MAX_TOOL_OUTPUT_TOKENS KASEKI_PHASE_OUTPUT_TOKEN_TARGET
  export KASEKI_PHASE_BUDGET_ENFORCEMENT
}
