import * as fs from 'fs';
import * as path from 'path';
import { FailureArtifactWriter } from './failure-artifact-writer';
import { Job } from '../kaseki-api-types';

const tempDirs: string[] = [];

function createResultsDir(): string {
  const dir = fs.mkdtempSync('/tmp/kaseki-failure-artifact-test-');
  tempDirs.push(dir);
  return dir;
}

function cleanupResultsDirs(): void {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
}

function createMockJob(overrides?: Partial<Job>): Job {
  return {
    id: 'job-123',
    status: 'failed',
    failureClass: 'spawn_error',
    exitCode: 1,
    error: 'Test error',
    request: {
      repoUrl: 'https://github.com/org/repo',
      ref: 'main',
    },
    createdAt: new Date(),
    completedAt: new Date(),
    resultDir: '/tmp/result',
    correlationId: 'corr-123',
    requestId: 'req-123',
    finalized: true,
    ...overrides,
  } as unknown as Job;
}

describe('FailureArtifactWriter', () => {
  let debugSpy: jest.SpyInstance;
  let errorSpy: jest.SpyInstance;

  beforeEach(() => {
    debugSpy = jest.spyOn(console, 'debug').mockImplementation(() => undefined);
    errorSpy = jest.spyOn(console, 'error').mockImplementation(() => undefined);
  });

  afterEach(() => {
    debugSpy.mockRestore();
    errorSpy.mockRestore();
    cleanupResultsDirs();
  });

  describe('writeFailureArtifacts with separate stdout and stderr buffers', () => {
    test('writes both stdout and stderr to stderr.log with proper separation', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      const stdoutTail = Buffer.from('This is stdout content\nLine 2 of stdout\n');
      const stderrTail = Buffer.from('This is stderr content\nLine 2 of stderr\n');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stdoutTail,
        stderrTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      expect(fs.existsSync(stderrLogPath)).toBe(true);

      const content = fs.readFileSync(stderrLogPath, 'utf-8');
      expect(content).toContain('stderr fallback generated by API finalization');
      expect(content).toContain('--- captured stderr tail ---');
      expect(content).toContain('This is stderr content');
      expect(content).toContain('--- captured stdout tail ---');
      expect(content).toContain('This is stdout content');
      expect(content).toContain(`failureClass=${job.failureClass}`);
      expect(content).toContain(`exitCode=${job.exitCode}`);
    });

    test('writes stderr.log with only stderr data when stdout is empty', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      const stderrTail = Buffer.from('Error output only\n');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stderrTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      expect(content).toContain('--- captured stderr tail ---');
      expect(content).toContain('Error output only');
      expect(content).not.toContain('--- captured stdout tail ---');
    });

    test('writes stderr.log with only stdout data when stderr is empty', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      const stdoutTail = Buffer.from('Output only\n');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stdoutTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      expect(content).toContain('--- captured stdout tail ---');
      expect(content).toContain('Output only');
      expect(content).not.toContain('--- captured stderr tail ---');
    });

    test('writes stderr.log without streams when both buffers are undefined', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      writer.writeFailureArtifacts(job, { attempted: true, ok: false });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      expect(content).toContain('stderr fallback generated by API finalization');
      expect(content).not.toContain('--- captured stderr tail ---');
      expect(content).not.toContain('--- captured stdout tail ---');
    });

    test('preserves multiline content with proper formatting', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      const stdoutTail = Buffer.from('Line 1\nLine 2\nLine 3\n');
      const stderrTail = Buffer.from('Error 1\nError 2\nError 3\n');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stdoutTail,
        stderrTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      // Verify all lines are present
      expect(content).toContain('Line 1\nLine 2\nLine 3');
      expect(content).toContain('Error 1\nError 2\nError 3');
    });

    test('handles UTF-8 encoded buffers correctly', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      const stdoutTail = Buffer.from('stdout with UTF-8: café résumé');
      const stderrTail = Buffer.from('stderr with UTF-8: naïve façade');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stdoutTail,
        stderrTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      expect(content).toContain('café résumé');
      expect(content).toContain('naïve façade');
    });

    test('includes failure metadata in stderr.log', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob({
        failureClass: 'timeout',
        exitCode: 124,
        error: 'Agent timeout after 3600 seconds',
      });

      const stdoutTail = Buffer.from('stdout content');
      const stderrTail = Buffer.from('stderr content');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stdoutTail,
        stderrTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      expect(content).toContain('failureClass=timeout');
      expect(content).toContain('exitCode=124');
      expect(content).toContain('error=Agent timeout after 3600 seconds');
    });

    test('handles large buffer content while maintaining separation', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      // Create large buffers (10 KB each)
      const stdoutTail = Buffer.alloc(10240, 'A');
      const stderrTail = Buffer.alloc(10240, 'B');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        stdoutTail,
        stderrTail,
      });

      const stderrLogPath = path.join(resultsDir, job.id, 'stderr.log');
      const content = fs.readFileSync(stderrLogPath, 'utf-8');

      // Verify both sections are present and separated
      expect(content).toContain('--- captured stderr tail ---');
      expect(content).toContain('--- captured stdout tail ---');

      // Verify approximate content sizes
      const stderrMatch = content.match(/--- captured stderr tail ---\s*(.+?)\n--- captured stdout tail ---/s);
      expect(stderrMatch).toBeTruthy();
    });
  });

  describe('writeFailureArtifacts with other options', () => {
    test('includes lastStage when provided in options', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      writer.writeFailureArtifacts(job, { attempted: true, ok: false }, {
        lastStage: 'scouting',
      });

      const analysisPath = path.join(resultsDir, job.id, 'analysis.md');
      expect(fs.existsSync(analysisPath)).toBe(true);
    });

    test('creates result directory if it does not exist', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      writer.writeFailureArtifacts(job, { attempted: true, ok: false });

      const resultDir = path.join(resultsDir, job.id);
      expect(fs.existsSync(resultDir)).toBe(true);
      expect(fs.statSync(resultDir).isDirectory()).toBe(true);
    });

    test('writes multiple artifact files', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      writer.writeFailureArtifacts(job, { attempted: true, ok: false });

      const resultDir = path.join(resultsDir, job.id);
      expect(fs.existsSync(path.join(resultDir, 'failure.json'))).toBe(true);
      expect(fs.existsSync(path.join(resultDir, 'result-summary.md'))).toBe(true);
      expect(fs.existsSync(path.join(resultDir, 'analysis.md'))).toBe(true);
      expect(fs.existsSync(path.join(resultDir, 'metadata.json'))).toBe(true);
      expect(fs.existsSync(path.join(resultDir, 'stderr.log'))).toBe(true);
    });

    test('emits structured atomic write stage logs for successful writes', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      writer.writeFailureArtifacts(job, { attempted: true, ok: false });

      const events = debugSpy.mock.calls
        .filter(([message]) => typeof message === 'string' && (message as string).startsWith('[file-helpers]'))
        .map(([message]) => (message as string).replace('[file-helpers] ', ''));

      expect(events).toContain('ensure_parent_dir');
      expect(events).toContain('exclusive_create_start');
      expect(events).toContain('exclusive_create_success');
      const firstPayload = debugSpy.mock.calls.find(([message]) =>
        typeof message === 'string' && (message as string).includes('exclusive_create_start')
      )?.[1] as Record<string, unknown>;
      expect(firstPayload.operation).toBe('writeIfMissingAtomic');
      expect(firstPayload.filePath).toContain(job.id);
      expect(firstPayload.jobId).toBe(job.id);
    });
  });

  describe('writeFailureArtifacts concurrency', () => {
    test('concurrent finalize/failure paths leave a consistent artifact set', async () => {
      const resultsDir = createResultsDir();
      const job = createMockJob({
        id: 'job-concurrent-artifacts',
        completedAt: new Date('2026-05-30T00:00:00.000Z'),
      });
      const resultDir = path.join(resultsDir, job.id);
      fs.mkdirSync(resultDir, { recursive: true });

      for (const artifactName of ['failure.json', 'metadata.json', 'stderr.log']) {
        fs.writeFileSync(path.join(resultDir, artifactName), '');
      }

      const attempts = Array.from({ length: 30 }, (_, idx) =>
        new Promise<void>((resolve) => {
          setImmediate(() => {
            const writer = new FailureArtifactWriter(resultsDir);
            writer.writeFailureArtifacts(
              {
                ...job,
                error: `concurrent error ${idx}`,
                exitCode: idx,
              } as Job,
              { attempted: true, ok: idx % 2 === 0, detail: `cleanup-${idx}` },
              {
                stdoutTail: Buffer.from(`stdout-${idx}`),
                stderrTail: Buffer.from(`stderr-${idx}`),
                lastStage: `stage-${idx}`,
              }
            );
            resolve();
          });
        })
      );

      await Promise.all(attempts);

      const failure = JSON.parse(fs.readFileSync(path.join(resultDir, 'failure.json'), 'utf-8')) as Record<string, unknown>;
      const metadata = JSON.parse(fs.readFileSync(path.join(resultDir, 'metadata.json'), 'utf-8')) as Record<string, unknown>;
      const stderrLog = fs.readFileSync(path.join(resultDir, 'stderr.log'), 'utf-8');

      expect(failure.failureClass).toBe('spawn_error');
      expect(failure.completedAt).toBe('2026-05-30T00:00:00.000Z');
      expect(metadata.id).toBe(job.id);
      expect(stderrLog).toContain('stderr fallback generated by API finalization');

      // result-summary.md and analysis.md removed in Phase 1 artifact cleanup
      expect(fs.existsSync(path.join(resultDir, 'result-summary.md'))).toBe(false);
      expect(fs.existsSync(path.join(resultDir, 'analysis.md'))).toBe(false);

      const leftovers = fs.readdirSync(resultDir).filter((name) => name.endsWith('.empty.lock') || name.includes('.tmp'));
      expect(leftovers).toEqual([]);
    });
  });

  describe('writeFailureArtifacts error handling', () => {
    test('does not write artifacts if job status is not failed', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob({
        status: 'completed',
        failureClass: undefined,
      });

      writer.writeFailureArtifacts(job, { attempted: true, ok: true });

      const resultDir = path.join(resultsDir, job.id);
      expect(fs.existsSync(resultDir)).toBe(false);
    });

    test('gracefully handles write errors without throwing', () => {
      // Use a directory that cannot be written to
      const resultsDir = '/root/.kaseki-cant-write-here';
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();

      // This should not throw even though we can't write
      expect(() => {
        writer.writeFailureArtifacts(job, { attempted: true, ok: false });
      }).not.toThrow();
    });

    test('logs errno-style failure context for duplicate artifacts', () => {
      const resultsDir = createResultsDir();
      const writer = new FailureArtifactWriter(resultsDir);
      const job = createMockJob();
      const resultDir = path.join(resultsDir, job.id);
      fs.mkdirSync(resultDir, { recursive: true });
      fs.writeFileSync(path.join(resultDir, 'failure.json'), '{"existing":true}\n');

      writer.writeFailureArtifacts(job, { attempted: true, ok: false });

      const structuredErrors = debugSpy.mock.calls.filter(
        ([message]) => typeof message === 'string' && (message as string).includes('write_error_context')
      );
      expect(structuredErrors.length).toBeGreaterThan(0);
      expect(structuredErrors.some(([, payload]) => String((payload as Record<string, unknown>).filePath).includes('failure.json'))).toBe(
        true
      );
      expect(
        structuredErrors.some(([, payload]) => (payload as Record<string, unknown>).errorMessage === 'File already exists, is non-empty, or another writer won the artifact race')
      ).toBe(true);
      expect(errorSpy).toHaveBeenCalled();
    });
  });
});
