#!/usr/bin/env node
/** Offline, read-only calibration report for historical run-scorecard artifacts. */
import fs from 'node:fs';
import path from 'node:path';

interface Card { overall_score?: number; rubric_version?: string; scoring_config?: { task_size?: string }; dimensions?: Array<{id?:string;normalized_score?:number}>; timing_totals?:{wall_clock_ms?:number}; token_totals?:Record<string,number>; model?:string }
interface Row { band:string; model:string; rubric:string; score:number; duration:number; tokens:number; dimensions:Record<string,number> }
const percentile=(values:number[], p:number):number => { if(!values.length)return 0; const sorted=[...values].sort((a,b)=>a-b); return sorted[Math.min(sorted.length-1,Math.floor((sorted.length-1)*p))]; };
function find(root:string):string[]{ const found:string[]=[]; const visit=(dir:string)=>{ for(const entry of fs.readdirSync(dir,{withFileTypes:true})){ const file=path.join(dir,entry.name); if(entry.isDirectory())visit(file); else if(entry.name==='run-scorecard.json')found.push(file); } }; visit(root); return found.sort(); }
function group(rows:Row[], key:(row:Row)=>string){ return Object.fromEntries([...new Set(rows.map(key))].sort().map(value=>{const selected=rows.filter(row=>key(row)===value);return [value,{runs:selected.length,score:{p10:percentile(selected.map(r=>r.score),.1),median:percentile(selected.map(r=>r.score),.5),p90:percentile(selected.map(r=>r.score),.9)},recommended_targets:{duration_seconds_p75:Math.round(percentile(selected.map(r=>r.duration),.75)/1000),tokens_p75:Math.round(percentile(selected.map(r=>r.tokens),.75))}}]})); }
export function calibrate(root:string){ const invalid:string[]=[]; const rows:Row[]=[]; for(const file of find(root)){try{const c=JSON.parse(fs.readFileSync(file,'utf8')) as Card;if(typeof c.overall_score!=='number')throw new Error('missing score');const usage=c.token_totals??{};let metadata:Record<string,unknown>={};try{metadata=JSON.parse(fs.readFileSync(path.join(path.dirname(file),'metadata.json'),'utf8')) as Record<string,unknown>;}catch{/* optional sibling */}rows.push({band:c.scoring_config?.task_size??'unknown',model:c.model??String(metadata.actual_model??metadata.model??metadata.selected_model??'unknown'),rubric:c.rubric_version??'unknown',score:c.overall_score,duration:c.timing_totals?.wall_clock_ms??0,tokens:['input_tokens','output_tokens','cache_read_tokens','cache_write_tokens'].reduce((n,k)=>n+(usage[k]??0),0),dimensions:Object.fromEntries((c.dimensions??[]).map(d=>[d.id??'unknown',d.normalized_score??0]))});}catch{invalid.push(file);}}
  const ids=[...new Set(rows.flatMap(r=>Object.keys(r.dimensions)))].sort(); const discrimination=Object.fromEntries(ids.map(id=>{const values=rows.map(r=>r.dimensions[id]).filter((v):v is number=>typeof v==='number');return[id,{range:values.length?Math.max(...values)-Math.min(...values):0,standard_deviation:Number(Math.sqrt(values.reduce((n,v)=>n+(v-(values.reduce((a,b)=>a+b,0)/values.length))**2,0)/(values.length||1)).toFixed(2)),low_discrimination:values.length>1&&Math.max(...values)-Math.min(...values)<10}]}));
  return {source:path.resolve(root),read_only:true,runs:rows.length,invalid_files:invalid,distributions:{task_size:group(rows,r=>r.band),model:group(rows,r=>r.model),rubric_version:group(rows,r=>r.rubric)},dimension_discrimination:discrimination}; }
if(process.argv[1]?.includes('calibrate-scorecards')){const root=process.argv[2];if(!root){console.error('Usage: calibrate-scorecards <historical-results-directory>');process.exitCode=2;}else console.log(JSON.stringify(calibrate(root),null,2));}
