import { spawnSync, type SpawnSyncReturns } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  resolveGatewayApiKey,
  shouldRunGatewayResponseSmoke,
  shouldRunPiProviderSmoke,
  resolveGatewayModel,
  isCloudflareGateway,
  buildStage1ProbeRequest,
  isResponsesEndpoint,
  isInvalidGatewayPathError,
  type GatewayTestOptions,
} from './gateway-detection/detect-gateway-provider';
import {
  analyzeResponseStructure,
  extractSampleEventStructure,
  countPiJsonEvents,
} from './gateway-validation/analyze-gateway-response';
import {
  extractPiJsonAssistantText,
  fetchWithTimeout,
} from './gateway-validation/extract-pi-json';
import {
  testGatewayResponseSmokeFull,
} from './gateway-validation/gateway-response-smoke-checks';

/**
 * LLM Gateway Responsiveness Test
 *
 * Validates that the configured LLM gateway is:
 * 1. Reachable (network connectivity)
 * 2. Responsive (returns HTTP responses)
 * 3. Authenticated (API key is accepted)
 *
 * This is a lightweight test for standard gateways; Cloudflare /compat gateways require
 * a minimal chat-completions probe because they do not expose an unscoped /models route.
 */

/**
 * Stage 1: Lightweight connectivity test result (reachability + authentication)
 * Tests /models endpoint to validate gateway is up and API key works. Cloudflare /compat
 * gateways use a minimal chat-completions probe because /v1/models is not valid there.
 */
export interface ConnectivityTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Gateway is responsive (1234ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /models request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /models endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /models endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
  attempts?: number; // Number of bounded connectivity attempts made
  retryDelayMs?: number; // Backoff used before the final attempt
  errorKind?: 'timeout' | 'network' | 'aborted' | 'unexpected';
}

/**
 * Stage 2: Full response validation test result (model inference smoke test)
 * Tests /responses endpoint with the resolved gateway model to validate inference
 * CONSUMES inference tokens - only run when explicitly triggered
 */
export interface ResponseSmokeTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Model generated valid response (9586ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /responses request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /responses endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /responses endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
  responseId?: string; // Response ID from gateway (e.g., "resp_xyz")
  outputTokens?: number; // Tokens generated by model
  modelUsed?: string; // Which model handled the request (if available)
  streamSmokeValidated?: boolean; // Streaming Responses API produced deltas or final assistant text
  largePromptSmokeValidated?: boolean; // Larger agent-shaped prompt produced assistant text
  checks?: ResponseSmokeSubcheck[]; // Per-contract smoke diagnostics
}

export interface ResponseSmokeSubcheck {
  name: 'json-response' | 'streaming-response' | 'large-prompt-response' | 'pi-provider-response' | 'cloudflare-compat-note';
  status: 'ok' | 'error';
  detail: string;
  responseTime: number;
  responseId?: string;
  outputTokens?: number;
}

export interface PiProviderSmokeTestResult {
  status: 'ok' | 'error' | 'skipped';
  detail: string;
  responseTime: number;
  timestamp: string;
  provider: 'gateway';
  model: string;
  outputEventCount?: number;
  assistantTextChars?: number;
  codingShapeValidated?: boolean;
  toolCallCount?: number;
  turnCount?: number;
  multiTurnValidated?: boolean;
  exitCode?: number | null;
  remediation?: string;
  diagnostics?: {
    fieldsSearched?: string[];
    fieldsFound?: string[];
    eventsByType?: Record<string, number>;
    eventsWithText?: number;
    assistantEventsWithText?: number;
    nonAssistantEventsWithText?: number;
    assistantFieldsFound?: string[];
    nonAssistantFieldsFound?: string[];
    suggestedPatterns?: string[];
    sampleEventStructure?: any;
    debugOutputPath?: string;
    rawAssistantPreview?: string;
  };
}

/**
 * Orchestrated full test result (stage 1 + stage 2)
 * Combines both stages with metadata about why stage 2 was skipped/run
 */
export interface FullGatewayTestResult {
  stage1: ConnectivityTestResult;
  stage2?: ResponseSmokeTestResult; // Only present if stage 2 ran
  orchestrationMetadata: {
    skippedStage2Reason?: string; // e.g., "Development environment", "Token consumption not desired"
    stage2Requested?: boolean; // Was stage 2 explicitly requested via options or query param?
    environmentDetected: string; // e.g., "production", "development", "test"
  };
}

/**
 * @deprecated Use ConnectivityTestResult or ResponseSmokeTestResult instead
 * Legacy result type for backward compatibility
 */
export interface GatewayTestResult {
  status: 'ok' | 'error';
  detail: string;
  gatewayUrl?: string;
  responseTime: number; // milliseconds
  timestamp: string; // ISO 8601
  authenticationValidated: boolean;
  remediation?: string;
  httpStatus?: number;
  warning?: string;
  responseSmokeValidated?: boolean;
  responseId?: string;
  outputTokens?: number;
}

const GATEWAY_LATENCY_WARNING_MS = 5000;
// Timeout for /models endpoint (lightweight check)
const GATEWAY_MODELS_TIMEOUT_MS = 10000;
const GATEWAY_CONNECTIVITY_ATTEMPTS = 2;
const GATEWAY_CONNECTIVITY_RETRY_DELAY_MS = 250;
const PI_PROVIDER_SMOKE_TIMEOUT_MS = (() => {
  const envValue = process.env.KASEKI_PI_PROVIDER_SMOKE_TIMEOUT_MS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  return 60000;
})();
const PI_PROVIDER_SMOKE_MAX_OUTPUT_TOKENS = (() => {
  const envValue = process.env.KASEKI_PI_PROVIDER_SMOKE_MAX_OUTPUT_TOKENS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  // The smoke must sustain a tool call and a follow-up assistant turn. A
  // 128-token ceiling frequently ends the turn before Pi can complete that
  // contract, producing a misleading adapter failure.
  return 512;
})();

// Re-export GatewayApiKeyResolution and GatewayTestOptions from detection module for backward compatibility
export type { GatewayApiKeyResolution, GatewayTestOptions } from './gateway-detection/detect-gateway-provider';
export { resolveGatewayApiKey, detectGatewayTestEnvironment, shouldRunGatewayResponseSmoke, shouldRunPiProviderSmoke, resolveGatewayModel } from './gateway-detection/detect-gateway-provider';

/**
 * Options for Pi provider smoke test
 */
export interface PiProviderSmokeTestOptions {
  requested?: boolean;
  debug?: boolean; // Log full response and diagnostics
}

type PiProviderSmokeConfig =
  | { ok: true; gatewayUrl: string; apiKey: string; model: string; timestamp: string }
  | { ok: false; result: PiProviderSmokeTestResult };

type PiProviderSmokeChild = SpawnSyncReturns<string>;

type GatewayConnectivityConfig =
  | { ok: true; gatewayUrl: string; apiKey: string }
  | { ok: false; result: ConnectivityTestResult };

function latencyWarning(responseTime: number): string | undefined {
  return responseTime >= GATEWAY_LATENCY_WARNING_MS
    ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
    : undefined;
}

function validateGatewayConnectivityConfig(timestamp: string): GatewayConnectivityConfig {
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      ok: false,
      result: {
        status: 'error',
        detail: 'LLM_GATEWAY_URL is not configured',
        gatewayUrl: '',
        responseTime: 0,
        timestamp,
        authenticationValidated: false,
        remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
      },
    };
  }

  if (!apiKey) {
    return {
      ok: false,
      result: {
        status: 'error',
        detail: 'LLM_GATEWAY_API_KEY is not configured',
        gatewayUrl,
        responseTime: 0,
        timestamp,
        authenticationValidated: false,
        remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
      },
    };
  }

  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      ok: false,
      result: {
        status: 'error',
        detail: `Gateway URL is invalid: ${gatewayUrl}`,
        gatewayUrl,
        responseTime: 0,
        timestamp,
        authenticationValidated: false,
        remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
      },
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      ok: false,
      result: {
        status: 'error',
        detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
        gatewayUrl,
        responseTime: 0,
        timestamp,
        authenticationValidated: false,
        remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
      },
    };
  }

  return { ok: true, gatewayUrl, apiKey };
}

async function runGatewayStage1Probe(
  gatewayUrl: string,
  timestamp: string,
  startTime: number,
): Promise<ConnectivityTestResult> {
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  for (let attempt = 1; ; attempt++) {
    try {
      const { response, responseTime } = await executeGatewayStage1Fetch(stage1Probe);

      if (!response.ok) {
        const errorBody = await response.text();
        return stage1HttpErrorResult({
          gatewayUrl,
          timestamp,
          responseTime,
          status: response.status,
          errorBody,
          attempts: attempt,
        });
      }

      return stage1SuccessResult(gatewayUrl, timestamp, responseTime, attempt);
    } catch (error) {
      const responseTime = Math.round(performance.now() - startTime);
      const errorMessage = error instanceof Error ? error.message : String(error);
      const errorKind = classifyStage1ProbeError(errorMessage);

      if (shouldRetryStage1Probe(attempt, errorKind)) {
        await new Promise((resolve) => setTimeout(resolve, GATEWAY_CONNECTIVITY_RETRY_DELAY_MS));
        continue;
      }

      return stage1FetchErrorResult(gatewayUrl, timestamp, responseTime, attempt, errorMessage, errorKind);
    }
  }
}

async function executeGatewayStage1Fetch(
  stage1Probe: ReturnType<typeof buildStage1ProbeRequest>,
): Promise<{ response: Response; responseTime: number }> {
  const fetchStartTime = performance.now();
  const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);
  return {
    response,
    responseTime: Math.round(performance.now() - fetchStartTime),
  };
}

function stage1SuccessResult(
  gatewayUrl: string,
  timestamp: string,
  responseTime: number,
  attempt: number,
): ConnectivityTestResult {
  const warning = latencyWarning(responseTime);
  return {
    status: 'ok',
    detail: `Gateway is responsive (${responseTime}ms)`,
    gatewayUrl,
    responseTime,
    timestamp,
    authenticationValidated: true,
    ...(warning ? { warning } : {}),
    attempts: attempt,
  };
}

function stage1HttpErrorResult(options: {
  gatewayUrl: string;
  timestamp: string;
  responseTime: number;
  status: number;
  errorBody: string;
  attempts: number;
}): ConnectivityTestResult {
  const authError = options.status === 401 || options.status === 403;
  const invalidPathError = isInvalidGatewayPathError(options.errorBody);

  return {
    status: 'error',
    detail: `Gateway returned HTTP ${options.status}: ${options.errorBody.substring(0, 100)}`,
    gatewayUrl: options.gatewayUrl,
    responseTime: options.responseTime,
    timestamp: options.timestamp,
    authenticationValidated: !authError && !invalidPathError,
    httpStatus: options.status,
    remediation: stage1HttpRemediation(options.status, authError, invalidPathError),
    attempts: options.attempts,
  };
}

function stage1HttpRemediation(status: number, authError: boolean, invalidPathError: boolean): string {
  if (authError) {
    return 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token';
  }
  if (invalidPathError) {
    return 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.';
  }
  return `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${status})`;
}

type Stage1ProbeErrorKind = 'timeout' | 'aborted' | 'network' | 'unexpected';

function classifyStage1ProbeError(errorMessage: string): Stage1ProbeErrorKind {
  if (/timeout/i.test(errorMessage)) return 'timeout';
  if (/abort/i.test(errorMessage)) return 'aborted';
  if (/fetch|ECONNREFUSED|ENOTFOUND|EAI_AGAIN|ECONNRESET/i.test(errorMessage)) return 'network';
  return 'unexpected';
}

function shouldRetryStage1Probe(attempt: number, errorKind: Stage1ProbeErrorKind): boolean {
  return attempt < GATEWAY_CONNECTIVITY_ATTEMPTS && errorKind !== 'unexpected';
}

function stage1FetchErrorResult(
  gatewayUrl: string,
  timestamp: string,
  responseTime: number,
  attempt: number,
  errorMessage: string,
  errorKind: Stage1ProbeErrorKind,
): ConnectivityTestResult {
  return {
    status: 'error',
    detail: `Gateway is unreachable after ${attempt} attempt${attempt === 1 ? '' : 's'} (${errorKind}): ${errorMessage}`,
    gatewayUrl,
    responseTime,
    timestamp,
    authenticationValidated: false,
    remediation: stage1FetchErrorRemediation(errorKind),
    attempts: attempt,
    retryDelayMs: attempt > 1 ? GATEWAY_CONNECTIVITY_RETRY_DELAY_MS : undefined,
    errorKind,
  };
}

function stage1FetchErrorRemediation(errorKind: Stage1ProbeErrorKind): string {
  switch (errorKind) {
  case 'timeout':
    return 'Gateway timed out. Check gateway health, DNS/TLS reachability, and upstream latency before retrying.';
  case 'aborted':
    return 'The connectivity probe was aborted. Check controller egress, proxy timeouts, and gateway availability before retrying.';
  case 'network':
    return 'Cannot reach the gateway endpoint. Verify DNS, URL, firewall/proxy rules, and controller egress before retrying.';
  case 'unexpected':
    return 'Unexpected error connecting to gateway. Check controller logs and gateway health before retrying.';
  }
}

export function createPiProviderSmokeWorkspace(): string {
  const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'kaseki-pi-provider-smoke-'));
  fs.writeFileSync(path.join(workspace, 'package.json'), JSON.stringify({
    name: 'kaseki-pi-provider-smoke', private: true, version: '0.0.0',
  }) + '\n', { mode: 0o600 });
  return workspace;
}

/**
 * Verify Pi provider is registered and configured correctly
 */
export function verifyPiProviderRegistration(): {
  registered: boolean;
  apiType?: string;
  model?: string;
  baseUrl?: string;
  issues?: string[];
  } {
  const result: any = {
    registered: false,
    issues: [],
  };

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const model = resolveGatewayModel();

  if (!gatewayUrl) {
    result.issues.push('LLM_GATEWAY_URL not configured');
  }

  if (!process.env.LLM_GATEWAY_API_KEY && !process.env.LLM_GATEWAY_API_KEY_FILE) {
    result.issues.push('LLM_GATEWAY_API_KEY or LLM_GATEWAY_API_KEY_FILE not configured');
  }

  result.registered = result.issues.length === 0;
  result.apiType = isCloudflareGateway(gatewayUrl ?? '') ? 'openai-completions' : 'openai-responses';
  result.model = model;
  result.baseUrl = gatewayUrl;

  return result;
}

function normalizePiProviderSmokeOptions(
  requested: boolean | PiProviderSmokeTestOptions,
): Required<PiProviderSmokeTestOptions> {
  const options: PiProviderSmokeTestOptions = typeof requested === 'object' ? requested : { requested };
  return {
    requested: options.requested === true,
    debug: options.debug === true,
  };
}

function skippedPiProviderSmokeResult(timestamp: string, model: string): PiProviderSmokeTestResult {
  return {
    status: 'skipped',
    detail: 'Pi provider smoke skipped. It requires opt-in to conserve LLM gateway tokens.',
    responseTime: 0,
    timestamp,
    provider: 'gateway',
    model,
    remediation: 'Pi provider smoke is opt-in because it can consume gateway tokens. Add ?piProvider=true to the request, or set KASEKI_ALLOW_DEV_PI_PROVIDER_SMOKE=1 to enable for integration testing.',
  };
}

function resolvePiProviderSmokeConfig(
  timestamp: string,
  model: string,
  requestedSmoke: boolean,
): PiProviderSmokeConfig {
  if (!shouldRunPiProviderSmoke(requestedSmoke)) {
    return {
      ok: false,
      result: skippedPiProviderSmokeResult(timestamp, model),
    };
  }

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;
  if (!gatewayUrl || !apiKey) {
    return {
      ok: false,
      result: {
        status: 'error',
        detail: 'Pi provider smoke cannot run because LLM_GATEWAY_URL or LLM_GATEWAY_API_KEY is missing',
        responseTime: 0,
        timestamp,
        provider: 'gateway',
        model,
        remediation: 'Configure gateway URL and API key before running Pi provider smoke.',
      },
    };
  }

  return { ok: true, gatewayUrl, apiKey, model, timestamp };
}

function buildPiProviderSmokePrompt(): string {
  return [
    'You are the coding phase of an ephemeral repository agent.',
    'Synthetic task: inspect package.json and propose one concise documentation improvement.',
    'You must use the read tool to inspect package.json before answering. Do not modify files.',
    'This validates streamed tool calls and a subsequent assistant turn through the gateway.',
    'Return exactly one JSON object and no markdown:',
    '{"status":"ok","phase":"coding","changed_files":[],"summary":"kaseki pi provider smoke ok"}',
  ].join('\n');
}

function createPiProviderWorkspaceOrError(
  timestamp: string,
  model: string,
  startTime: number,
): { ok: true; workspace: string } | { ok: false; result: PiProviderSmokeTestResult } {
  try {
    return { ok: true, workspace: createPiProviderSmokeWorkspace() };
  } catch (error) {
    return {
      ok: false,
      result: {
        status: 'error',
        detail: `Pi provider smoke could not create its disposable workspace: ${error instanceof Error ? error.message : String(error)}`,
        responseTime: Math.round(performance.now() - startTime),
        timestamp,
        provider: 'gateway',
        model,
        remediation: 'Ensure the controller can create temporary directories before running the Pi provider smoke.',
      },
    };
  }
}

function cleanupPiProviderSmokeWorkspace(workspace: string): void {
  try {
    fs.rmSync(workspace, { recursive: true, force: true });
  } catch {
    // The diagnostic result is still valid if best-effort temporary cleanup fails.
  }
}

function runPiProviderSmokeChild(config: Extract<PiProviderSmokeConfig, { ok: true }>, workspace: string): PiProviderSmokeChild {
  return spawnSync('pi', ['--mode', 'json', '--no-session', '--provider', 'gateway', '--model', config.model, buildPiProviderSmokePrompt()], {
    encoding: 'utf8',
    timeout: PI_PROVIDER_SMOKE_TIMEOUT_MS,
    cwd: workspace,
    env: {
      ...process.env,
      LLM_GATEWAY_URL: config.gatewayUrl,
      LLM_GATEWAY_API_KEY: config.apiKey,
      LLM_GATEWAY_MAX_OUTPUT_TOKENS: String(PI_PROVIDER_SMOKE_MAX_OUTPUT_TOKENS),
    },
    // Pi JSON mode can emit cumulative message snapshots and provider metadata
    // well beyond Node's small default buffer even for this constrained prompt.
    // Keep the smoke bounded, but large enough to distinguish adapter failures
    // from child_process ENOBUFS transport failures.
    maxBuffer: 16 * 1024 * 1024,
  });
}

function debugPiProviderSmokeOutput(stdout: string): string | undefined {
  try {
    const debugPath = `/tmp/kaseki-pi-debug-${Date.now()}.jsonl`;
    fs.writeFileSync(debugPath, stdout);
    return debugPath;
  } catch {
    return undefined;
  }
}

function failedCodingContractDebugOutput(stdout: string): string | undefined {
  try {
    const diagnosticsDir = process.env.KASEKI_RESULTS_DIR || '/tmp';
    fs.mkdirSync(diagnosticsDir, { recursive: true });
    const debugOutputPath = `${diagnosticsDir}/pi-provider-smoke-failed-${Date.now()}.jsonl`;
    fs.writeFileSync(debugOutputPath, stdout, { mode: 0o600 });
    return debugOutputPath;
  } catch {
    return undefined;
  }
}

function piProviderChildErrorResult(
  child: PiProviderSmokeChild,
  responseTime: number,
  timestamp: string,
  model: string,
): PiProviderSmokeTestResult {
  const errorMessage = child.error?.message ?? 'Unknown child process error';
  const timedOut = errorMessage.includes('ETIMEDOUT');
  const outputOverflow = errorMessage.includes('ENOBUFS');
  return {
    status: 'error',
    detail: `Pi provider smoke failed to start or complete: ${errorMessage}`,
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    remediation: timedOut
      ? 'Pi provider smoke timed out. Check gateway latency and Pi provider registration.'
      : outputOverflow
        ? 'Pi produced excessive JSONL output during the smoke test. Inspect provider event amplification and keep cumulative event payloads bounded.'
        : errorMessage.includes('ENOENT')
          ? 'Check that Pi CLI is installed in the controller image.'
          : 'Check that the gateway provider extension loads and inspect the Pi adapter diagnostics.',
  };
}

function piProviderExitErrorResult(
  child: PiProviderSmokeChild,
  stdout: string,
  responseTime: number,
  timestamp: string,
  model: string,
): PiProviderSmokeTestResult {
  const stderr = child.stderr || '';
  return {
    status: 'error',
    detail: `Pi provider smoke exited ${child.status}: ${(stderr || stdout).slice(0, 240)}`,
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    remediation: 'Gateway HTTP smoke can pass while Pi provider registration fails. Check .gateway-diagnostics.jsonl and provider api type.',
  };
}

function missingAssistantTextResult(
  stdout: string,
  child: PiProviderSmokeChild,
  responseTime: number,
  timestamp: string,
  model: string,
  debugMode: boolean,
): PiProviderSmokeTestResult {
  const analysis = analyzeResponseStructure(stdout);
  const sampleEvent = extractSampleEventStructure(stdout);
  const debugOutputPath = debugMode ? debugPiProviderSmokeOutput(stdout) : undefined;

  return {
    status: 'error',
    detail: 'Pi provider smoke completed but produced no assistant text',
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    outputEventCount: countPiJsonEvents(stdout),
    assistantTextChars: 0,
    diagnostics: {
      fieldsSearched: [
        'message.text',
        'message.output_text',
        'message.assistantMessage',
        'message.content (string)',
        'message.choices[0].message.content',
        'message.choices[0].delta.content',
        'message.response.content',
      ],
      fieldsFound: analysis.fieldsFound,
      eventsByType: analysis.eventsByType,
      eventsWithText: analysis.eventsWithText,
      assistantEventsWithText: analysis.assistantEventsWithText,
      nonAssistantEventsWithText: analysis.nonAssistantEventsWithText,
      assistantFieldsFound: analysis.assistantFieldsFound,
      nonAssistantFieldsFound: analysis.nonAssistantFieldsFound,
      suggestedPatterns: analysis.suggestedPatterns,
      sampleEventStructure: sampleEvent,
      ...(debugOutputPath ? { debugOutputPath } : {}),
    },
    remediation:
      analysis.suggestedPatterns.length > 0
        ? `Found assistant response fields but text not extracted. Try patterns: ${analysis.suggestedPatterns.slice(0, 2).join(', ')}. Check Pi provider registration and gateway response format.`
        : analysis.nonAssistantFieldsFound.length > 0
          ? `Found text fields only on non-assistant messages (${analysis.nonAssistantFieldsFound.slice(0, 2).join(', ')}), but no assistant text was produced. Verify Pi provider api uses openai-responses and gateway assistant output is streamed with role=assistant.`
          : 'No assistant response fields found. Verify Pi provider api uses openai-responses and gateway is returning valid assistant responses.',
  };
}

/**
 * Process a character while inside a JSON string, tracking escape sequences.
 * Returns the updated escape state and whether we're still in the string.
 */
function processStringCharacter(
  character: string,
  escaped: boolean
): { escaped: boolean; inString: boolean } {
  if (escaped) {
    return { escaped: false, inString: true };
  }
  if (character === '\\') {
    return { escaped: true, inString: true };
  }
  if (character === '"') {
    return { escaped: false, inString: false };
  }
  return { escaped: false, inString: true };
}

/**
 * Find the end index of a JSON object starting at `start`, or -1 if malformed.
 * Handles nested braces and string escaping correctly.
 */
function findJsonObjectEnd(text: string, start: number): number {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = start; index < text.length; index += 1) {
    const character = text[index];

    if (inString) {
      const state = processStringCharacter(character, escaped);
      escaped = state.escaped;
      inString = state.inString;
      continue;
    }

    if (character === '"') {
      inString = true;
    } else if (character === '{') {
      depth += 1;
    } else if (character === '}') {
      depth -= 1;
      if (depth === 0) {
        return index;
      }
    }
  }

  return -1; // No matching closing brace found
}

/**
 * Try to parse a JSON object from text[start..end] and return it if valid.
 * Returns null if the slice is not a valid JSON object or is an array.
 */
function tryParseJsonObject(text: string, start: number, end: number): Record<string, unknown> | null {
  try {
    const value = JSON.parse(text.slice(start, end + 1));
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return value as Record<string, unknown>;
    }
  } catch {
    // Continue looking for a later, valid JSON object.
  }
  return null;
}

/**
 * Find JSON objects embedded in an assistant response without treating braces
 * inside JSON strings as object boundaries.
 */
function extractJsonObjects(text: string): Record<string, unknown>[] {
  const objects: Record<string, unknown>[] = [];

  for (let start = text.indexOf('{'); start !== -1; start = text.indexOf('{', start + 1)) {
    const end = findJsonObjectEnd(text, start);
    if (end === -1) {
      continue;
    }

    const obj = tryParseJsonObject(text, start, end);
    if (obj !== null) {
      objects.push(obj);
    }
  }

  return objects;
}

export function parseCodingShapeValidated(assistantText: string, multiTurnValidated: boolean): boolean {
  if (!multiTurnValidated) return false;

  return extractJsonObjects(assistantText).some(
    (smokePayload) => smokePayload.status === 'ok' && smokePayload.phase === 'coding',
  );
}

function codingContractErrorResult(
  stdout: string,
  assistantText: string,
  child: PiProviderSmokeChild,
  responseTime: number,
  timestamp: string,
  model: string,
  toolCallCount: number,
  turnCount: number,
  multiTurnValidated: boolean,
): PiProviderSmokeTestResult {
  const debugOutputPath = failedCodingContractDebugOutput(stdout);
  return {
    status: 'error',
    detail: 'Pi provider produced assistant text but did not satisfy the coding-shaped JSON contract',
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    outputEventCount: countPiJsonEvents(stdout),
    assistantTextChars: assistantText.trim().length,
    codingShapeValidated: false,
    toolCallCount,
    turnCount,
    multiTurnValidated,
    diagnostics: {
      ...(debugOutputPath ? { debugOutputPath } : {}),
      rawAssistantPreview: assistantText.trim().slice(0, 1000),
    },
    remediation: multiTurnValidated
      ? 'Inspect the gateway response body and Pi event stream; the multi-turn tool flow passed but the final coding contract failed.'
      : 'The gateway must sustain a streamed tool call and follow-up assistant turn. Inspect tool-call deltas, finish reasons, and adapter stream handling.',
  };
}

function analyzePiProviderSmokeChild(
  child: PiProviderSmokeChild,
  responseTime: number,
  timestamp: string,
  model: string,
  debugMode: boolean,
): PiProviderSmokeTestResult {
  const stdout = child.stdout || '';
  const assistantText = extractPiJsonAssistantText(stdout);
  const responseAnalysis = analyzeResponseStructure(stdout);
  const toolCallCount = responseAnalysis.eventsByType.tool_execution_start || 0;
  const turnCount = responseAnalysis.eventsByType.turn_start || 0;
  const multiTurnValidated = toolCallCount > 0 && turnCount >= 2;

  if (child.error) {
    return piProviderChildErrorResult(child, responseTime, timestamp, model);
  }

  if (child.status !== 0) {
    return piProviderExitErrorResult(child, stdout, responseTime, timestamp, model);
  }

  if (!assistantText.trim()) {
    return missingAssistantTextResult(stdout, child, responseTime, timestamp, model, debugMode);
  }

  const codingShapeValidated = parseCodingShapeValidated(assistantText, multiTurnValidated);
  if (!codingShapeValidated) {
    return codingContractErrorResult(stdout, assistantText, child, responseTime, timestamp, model, toolCallCount, turnCount, multiTurnValidated);
  }

  return {
    status: 'ok',
    detail: `Pi gateway provider produced assistant text (${responseTime}ms)`,
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    outputEventCount: countPiJsonEvents(stdout),
    assistantTextChars: assistantText.trim().length,
    codingShapeValidated,
    toolCallCount,
    turnCount,
    multiTurnValidated,
  };
}

export function testPiGatewayProviderSmoke(requested: boolean | PiProviderSmokeTestOptions = false): PiProviderSmokeTestResult {
  const timestamp = new Date().toISOString();
  const startTime = performance.now();
  const model = resolveGatewayModel();
  const options = normalizePiProviderSmokeOptions(requested);
  const config = resolvePiProviderSmokeConfig(timestamp, model, options.requested);

  if (!config.ok) return config.result;

  const workspace = createPiProviderWorkspaceOrError(timestamp, model, startTime);
  if (!workspace.ok) return workspace.result;

  const child = runPiProviderSmokeChild(config, workspace.workspace);
  cleanupPiProviderSmokeWorkspace(workspace.workspace);

  return analyzePiProviderSmokeChild(
    child,
    Math.round(performance.now() - startTime),
    timestamp,
    model,
    options.debug,
  );
}

/**
 * Stage 1: Lightweight gateway connectivity test
 * Tests reachability and authentication via /models endpoint
 * Does NOT consume inference tokens
 *
 * @returns ConnectivityTestResult with status and diagnostics
 */
export async function testGatewayConnectivity_Stage1(): Promise<ConnectivityTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();
  const config = validateGatewayConnectivityConfig(timestamp);

  if (!config.ok) return config.result;
  return runGatewayStage1Probe(config.gatewayUrl, timestamp, startTime);
}

/**
 * Test LLM gateway responsiveness
 *
 * @returns Gateway test result with status and diagnostics
 */
export async function testGatewayConnectivity(options: GatewayTestOptions = {}): Promise<GatewayTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();
  const config = validateGatewayConnectivityConfig(timestamp);

  if (!config.ok) {
    if (config.result.gatewayUrl) return config.result;
    const { gatewayUrl: _gatewayUrl, ...result } = config.result;
    return result;
  }

  const stage1Result = await runGatewayStage1Probe(config.gatewayUrl, timestamp, startTime);
  if (stage1Result.status === 'error') return stage1Result;

  if (shouldRunGatewayResponseSmoke(options)) {
    const smokeResult = await testGatewayResponseSmoke(config.gatewayUrl, config.apiKey, timestamp, startTime);
    if (smokeResult.status === 'error') return smokeResult;

    return {
      ...smokeResult,
      detail: `Gateway is responsive and returned usable Responses API content (${smokeResult.responseTime}ms)`,
      warning: stage1Result.warning,
    };
  }

  return {
    ...stage1Result,
    responseSmokeValidated: false,
  };
}

/**
 * Stage 2: Full response validation test
 * Tests model inference via /responses endpoint with the resolved gateway model
 * CONSUMES inference tokens - only call when explicitly requested
 *
 * @param gatewayUrl Base gateway URL (e.g., https://llmgateway.local.xyz/v1)
 * @param apiKey LLM gateway API key
 * @param timestamp ISO 8601 timestamp for the test
 * @param startTime Performance.now() from test start
 * @returns ResponseSmokeTestResult with inference details
 */
export async function testGatewayResponseSmoke_Stage2(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<ResponseSmokeTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, false);
}

async function testGatewayResponseSmoke(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<GatewayTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, true);
}

// Re-export builder functions from detection module for backward compatibility
export {
  isCloudflareGateway,
  buildModelsEndpoint,
  buildResponsesEndpoint,
  buildCloudflareInferenceEndpoint,
} from './gateway-detection/detect-gateway-provider';

// Re-export analysis functions from validation module
export { extractSampleEventStructure, analyzeResponseStructure } from './gateway-validation/analyze-gateway-response';
export { extractPiJsonAssistantText } from './gateway-validation/extract-pi-json';

// Re-export from detection module for backward compatibility
export { isResponsesEndpoint } from './gateway-detection/detect-gateway-provider';

// Re-export from extraction module for backward compatibility
export { formatGatewayTestResponse } from './gateway-validation/extract-pi-json';
