import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import {
  resolveGatewayApiKey,
  shouldRunGatewayResponseSmoke,
  shouldRunPiProviderSmoke,
  resolveGatewayModel,
  isCloudflareGateway,
  buildStage1ProbeRequest,
  buildResponsesEndpoint,
  isResponsesEndpoint,
  isInvalidGatewayPathError,
  type GatewayTestOptions,
} from './gateway-detection/detect-gateway-provider';
import {
  extractOutputTokens,
  parseResponsesSse,
  extractSampleEventStructure,
  countPiJsonEvents,
  analyzeResponseStructure,
} from './gateway-validation/analyze-gateway-response';
import {
  extractPiJsonAssistantText,
  fetchWithTimeout,
} from './gateway-validation/extract-pi-json';

/**
 * LLM Gateway Responsiveness Test
 *
 * Validates that the configured LLM gateway is:
 * 1. Reachable (network connectivity)
 * 2. Responsive (returns HTTP responses)
 * 3. Authenticated (API key is accepted)
 *
 * This is a lightweight test for standard gateways; Cloudflare /compat gateways require
 * a minimal chat-completions probe because they do not expose an unscoped /models route.
 */

/**
 * Stage 1: Lightweight connectivity test result (reachability + authentication)
 * Tests /models endpoint to validate gateway is up and API key works. Cloudflare /compat
 * gateways use a minimal chat-completions probe because /v1/models is not valid there.
 */
export interface ConnectivityTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Gateway is responsive (1234ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /models request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /models endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /models endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
}

/**
 * Stage 2: Full response validation test result (model inference smoke test)
 * Tests /responses endpoint with the resolved gateway model to validate inference
 * CONSUMES inference tokens - only run when explicitly triggered
 */
export interface ResponseSmokeTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Model generated valid response (9586ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /responses request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /responses endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /responses endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
  responseId?: string; // Response ID from gateway (e.g., "resp_xyz")
  outputTokens?: number; // Tokens generated by model
  modelUsed?: string; // Which model handled the request (if available)
  streamSmokeValidated?: boolean; // Streaming Responses API produced deltas or final assistant text
  largePromptSmokeValidated?: boolean; // Larger agent-shaped prompt produced assistant text
  checks?: ResponseSmokeSubcheck[]; // Per-contract smoke diagnostics
}

export interface ResponseSmokeSubcheck {
  name: 'json-response' | 'streaming-response' | 'large-prompt-response' | 'pi-provider-response' | 'cloudflare-compat-note';
  status: 'ok' | 'error';
  detail: string;
  responseTime: number;
  responseId?: string;
  outputTokens?: number;
}

export interface PiProviderSmokeTestResult {
  status: 'ok' | 'error' | 'skipped';
  detail: string;
  responseTime: number;
  timestamp: string;
  provider: 'gateway';
  model: string;
  outputEventCount?: number;
  assistantTextChars?: number;
  exitCode?: number | null;
  remediation?: string;
  diagnostics?: {
    fieldsSearched?: string[];
    fieldsFound?: string[];
    eventsByType?: Record<string, number>;
    eventsWithText?: number;
    assistantEventsWithText?: number;
    nonAssistantEventsWithText?: number;
    assistantFieldsFound?: string[];
    nonAssistantFieldsFound?: string[];
    suggestedPatterns?: string[];
    sampleEventStructure?: any;
    debugOutputPath?: string;
  };
}

/**
 * Orchestrated full test result (stage 1 + stage 2)
 * Combines both stages with metadata about why stage 2 was skipped/run
 */
export interface FullGatewayTestResult {
  stage1: ConnectivityTestResult;
  stage2?: ResponseSmokeTestResult; // Only present if stage 2 ran
  orchestrationMetadata: {
    skippedStage2Reason?: string; // e.g., "Development environment", "Token consumption not desired"
    stage2Requested?: boolean; // Was stage 2 explicitly requested via options or query param?
    environmentDetected: string; // e.g., "production", "development", "test"
  };
}

/**
 * @deprecated Use ConnectivityTestResult or ResponseSmokeTestResult instead
 * Legacy result type for backward compatibility
 */
export interface GatewayTestResult {
  status: 'ok' | 'error';
  detail: string;
  gatewayUrl?: string;
  responseTime: number; // milliseconds
  timestamp: string; // ISO 8601
  authenticationValidated: boolean;
  remediation?: string;
  httpStatus?: number;
  warning?: string;
  responseSmokeValidated?: boolean;
  responseId?: string;
  outputTokens?: number;
}

const GATEWAY_LATENCY_WARNING_MS = 5000;
// Timeout for /models endpoint (lightweight check)
const GATEWAY_MODELS_TIMEOUT_MS = 10000;
// Timeout for /responses endpoint (includes model inference)
// Default 45s allows for model selection, routing, and inference
const GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS = (() => {
  const envValue = process.env.KASEKI_GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  return 45000; // 45 second default
})();
const GATEWAY_RESPONSE_SMOKE_PROMPT = [
  'You are validating an OpenAI Responses API gateway for Kaseki agent prompts.',
  'Return exactly one JSON object with no markdown and no surrounding text.',
  'The JSON object must be: {"status":"ok","summary":"kaseki gateway smoke ok"}',
].join('\n');
const GATEWAY_RESPONSE_LARGE_SMOKE_PROMPT = [
  GATEWAY_RESPONSE_SMOKE_PROMPT,
  '',
  'Context sample:',
  ...Array.from({ length: 80 }, (_, index) =>
    `- file_${String(index + 1).padStart(2, '0')}.ts: inspect this synthetic repository note and preserve the required JSON-only response contract.`,
  ),
].join('\n');
const GATEWAY_RESPONSE_SMOKE_MAX_OUTPUT_TOKENS = 256;
const PI_PROVIDER_SMOKE_TIMEOUT_MS = (() => {
  const envValue = process.env.KASEKI_PI_PROVIDER_SMOKE_TIMEOUT_MS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  return 60000;
})();

// Re-export GatewayApiKeyResolution and GatewayTestOptions from detection module for backward compatibility
export type { GatewayApiKeyResolution, GatewayTestOptions } from './gateway-detection/detect-gateway-provider';
export { resolveGatewayApiKey, detectGatewayTestEnvironment, shouldRunGatewayResponseSmoke, shouldRunPiProviderSmoke, resolveGatewayModel } from './gateway-detection/detect-gateway-provider';

/**
 * Options for Pi provider smoke test
 */
export interface PiProviderSmokeTestOptions {
  requested?: boolean;
  debug?: boolean; // Log full response and diagnostics
}

/**
 * Verify Pi provider is registered and configured correctly
 */
export function verifyPiProviderRegistration(): {
  registered: boolean;
  apiType?: string;
  model?: string;
  baseUrl?: string;
  issues?: string[];
  } {
  const result: any = {
    registered: false,
    issues: [],
  };

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const model = resolveGatewayModel();

  if (!gatewayUrl) {
    result.issues.push('LLM_GATEWAY_URL not configured');
  }

  if (!process.env.LLM_GATEWAY_API_KEY && !process.env.LLM_GATEWAY_API_KEY_FILE) {
    result.issues.push('LLM_GATEWAY_API_KEY or LLM_GATEWAY_API_KEY_FILE not configured');
  }

  result.registered = result.issues.length === 0;
  result.apiType = 'openai-responses';
  result.model = model;
  result.baseUrl = gatewayUrl;

  return result;
}

export function testPiGatewayProviderSmoke(requested: boolean | PiProviderSmokeTestOptions = false): PiProviderSmokeTestResult {
  const timestamp = new Date().toISOString();
  const startTime = performance.now();
  const model = resolveGatewayModel();

  // Handle both boolean (backward compat) and options object
  const options: PiProviderSmokeTestOptions = typeof requested === 'object' ? requested : { requested };
  const debugMode = options.debug === true;
  const requestedSmoke = options.requested === true;

  if (!shouldRunPiProviderSmoke(requestedSmoke)) {
    const remediation = 'Pi provider smoke is opt-in because it can consume gateway tokens. Add ?piProvider=true to the request, or set KASEKI_ALLOW_DEV_PI_PROVIDER_SMOKE=1 to enable for integration testing.';

    return {
      status: 'skipped',
      detail: 'Pi provider smoke skipped. It requires opt-in to conserve LLM gateway tokens.',
      responseTime: 0,
      timestamp,
      provider: 'gateway',
      model,
      remediation,
    };
  }

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;
  if (!gatewayUrl || !apiKey) {
    return {
      status: 'error',
      detail: 'Pi provider smoke cannot run because LLM_GATEWAY_URL or LLM_GATEWAY_API_KEY is missing',
      responseTime: 0,
      timestamp,
      provider: 'gateway',
      model,
      remediation: 'Configure gateway URL and API key before running Pi provider smoke.',
    };
  }

  const prompt = [
    'Return exactly this plain text and nothing else:',
    'kaseki pi provider smoke ok',
  ].join('\n');
  const child = spawnSync('pi', ['--mode', 'json', '--no-session', '--provider', 'gateway', '--model', model, prompt], {
    encoding: 'utf8',
    timeout: PI_PROVIDER_SMOKE_TIMEOUT_MS,
    env: {
      ...process.env,
      LLM_GATEWAY_URL: gatewayUrl,
      LLM_GATEWAY_API_KEY: apiKey,
      LLM_GATEWAY_MAX_OUTPUT_TOKENS: '128',
    },
    maxBuffer: 1024 * 1024,
  });
  const responseTime = Math.round(performance.now() - startTime);
  const stdout = child.stdout || '';
  const stderr = child.stderr || '';
  const assistantText = extractPiJsonAssistantText(stdout);

  if (child.error) {
    const timedOut = child.error.message.includes('ETIMEDOUT');
    return {
      status: 'error',
      detail: `Pi provider smoke failed to start or complete: ${child.error.message}`,
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      remediation: timedOut
        ? 'Pi provider smoke timed out. Check gateway latency and Pi provider registration.'
        : 'Check that Pi CLI is installed in the controller/worker image and gateway provider extension loads.',
    };
  }

  if (child.status !== 0) {
    return {
      status: 'error',
      detail: `Pi provider smoke exited ${child.status}: ${(stderr || stdout).slice(0, 240)}`,
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      remediation: 'Gateway HTTP smoke can pass while Pi provider registration fails. Check .gateway-diagnostics.jsonl and provider api type.',
    };
  }

  if (!assistantText.trim()) {
    const analysis = analyzeResponseStructure(stdout);
    const sampleEvent = extractSampleEventStructure(stdout);

    let debugOutputPath: string | undefined;
    if (debugMode) {
      // In debug mode, persist raw response for diagnostics.
      try {
        const debugPath = `/tmp/kaseki-pi-debug-${Date.now()}.jsonl`;
        fs.writeFileSync(debugPath, stdout);
        debugOutputPath = debugPath;
      } catch {
        // Ignore write errors in debug mode
      }
    }

    return {
      status: 'error',
      detail: 'Pi provider smoke completed but produced no assistant text',
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      outputEventCount: countPiJsonEvents(stdout),
      assistantTextChars: 0,
      diagnostics: {
        fieldsSearched: [
          'message.text',
          'message.output_text',
          'message.assistantMessage',
          'message.content (string)',
          'message.choices[0].message.content',
          'message.choices[0].delta.content',
          'message.response.content',
        ],
        fieldsFound: analysis.fieldsFound,
        eventsByType: analysis.eventsByType,
        eventsWithText: analysis.eventsWithText,
        assistantEventsWithText: analysis.assistantEventsWithText,
        nonAssistantEventsWithText: analysis.nonAssistantEventsWithText,
        assistantFieldsFound: analysis.assistantFieldsFound,
        nonAssistantFieldsFound: analysis.nonAssistantFieldsFound,
        suggestedPatterns: analysis.suggestedPatterns,
        sampleEventStructure: sampleEvent,
        ...(debugOutputPath ? { debugOutputPath } : {}),
      },
      remediation:
        analysis.suggestedPatterns.length > 0
          ? `Found assistant response fields but text not extracted. Try patterns: ${analysis.suggestedPatterns.slice(0, 2).join(', ')}. Check Pi provider registration and gateway response format.`
          : analysis.nonAssistantFieldsFound.length > 0
            ? `Found text fields only on non-assistant messages (${analysis.nonAssistantFieldsFound.slice(0, 2).join(', ')}), but no assistant text was produced. Verify Pi provider api uses openai-responses and gateway assistant output is streamed with role=assistant.`
            : 'No assistant response fields found. Verify Pi provider api uses openai-responses and gateway is returning valid assistant responses.',
    };
  }

  return {
    status: 'ok',
    detail: `Pi gateway provider produced assistant text (${responseTime}ms)`,
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    outputEventCount: countPiJsonEvents(stdout),
    assistantTextChars: assistantText.trim().length,
  };
}

/**
 * Stage 1: Lightweight gateway connectivity test
 * Tests reachability and authentication via /models endpoint
 * Does NOT consume inference tokens
 *
 * @returns ConnectivityTestResult with status and diagnostics
 */
export async function testGatewayConnectivity_Stage1(): Promise<ConnectivityTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();

  // Check configuration
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_URL is not configured',
      gatewayUrl: '',
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
    };
  }

  if (!apiKey) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_API_KEY is not configured',
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
    };
  }

  // Validate URL format
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      status: 'error',
      detail: `Gateway URL is invalid: ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      status: 'error',
      detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
    };
  }

  // Make test request to the appropriate Stage 1 probe endpoint. Standard
  // OpenAI-compatible gateways can use /models; Cloudflare /compat gateways must
  // preserve the scoped /v1/{account_id}/{gateway_id}/compat path and probe chat completions.
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  try {
    const fetchStartTime = performance.now();
    const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);

    if (!response.ok) {
      const errorBody = await response.text();
      const authError = response.status === 401 || response.status === 403;
      const invalidPathError = isInvalidGatewayPathError(errorBody);

      return {
        status: 'error',
        detail: `Gateway returned HTTP ${response.status}: ${errorBody.substring(0, 100)}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: !authError && !invalidPathError,
        httpStatus: response.status,
        remediation: authError
          ? 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token'
          : invalidPathError
            ? 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.'
            : `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${response.status})`,
      };
    }

    // Successful response
    const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
      ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
      : undefined;
    return {
      status: 'ok',
      detail: `Gateway is responsive (${responseTime}ms)`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      ...(warning ? { warning } : {}),
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Network errors, timeouts, etc.
    const isTimeout = errorMessage.includes('timeout') || errorMessage.includes('Timeout');
    const isNetwork = errorMessage.includes('fetch') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('ENOTFOUND');

    return {
      status: 'error',
      detail: `Gateway is unreachable: ${errorMessage}`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: false,
      remediation: isTimeout
        ? 'Gateway is slow or not responding. Check gateway health and network connectivity'
        : isNetwork
          ? 'Cannot reach gateway endpoint. Verify the URL is reachable and check network/firewall rules'
          : 'Unexpected error connecting to gateway. Check logs for details',
    };
  }
}

/**
 * Test LLM gateway responsiveness
 *
 * @returns Gateway test result with status and diagnostics
 */
export async function testGatewayConnectivity(options: GatewayTestOptions = {}): Promise<GatewayTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();

  // Check configuration
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_URL is not configured',
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
    };
  }

  if (!apiKey) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_API_KEY is not configured',
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
    };
  }

  // Validate URL format
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      status: 'error',
      detail: `Gateway URL is invalid: ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      status: 'error',
      detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
    };
  }

  // Make test request to the appropriate Stage 1 probe endpoint. Standard
  // OpenAI-compatible gateways can use /models; Cloudflare /compat gateways must
  // preserve the scoped /v1/{account_id}/{gateway_id}/compat path and probe chat completions.
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  try {
    const fetchStartTime = performance.now();
    const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);

    if (!response.ok) {
      const errorBody = await response.text();
      const authError = response.status === 401 || response.status === 403;
      const invalidPathError = isInvalidGatewayPathError(errorBody);

      return {
        status: 'error',
        detail: `Gateway returned HTTP ${response.status}: ${errorBody.substring(0, 100)}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: !authError && !invalidPathError,
        httpStatus: response.status,
        remediation: authError
          ? 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token'
          : invalidPathError
            ? 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.'
            : `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${response.status})`,
      };
    }

    if (shouldRunGatewayResponseSmoke(options)) {
      const smokeResult = await testGatewayResponseSmoke(gatewayUrl, apiKey, timestamp, startTime);
      if (smokeResult.status === 'error') return smokeResult;

      const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
        ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
        : undefined;
      return {
        ...smokeResult,
        detail: `Gateway is responsive and returned usable Responses API content (${smokeResult.responseTime}ms)`,
        warning,
      };
    }

    // Successful response
    const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
      ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
      : undefined;
    return {
      status: 'ok',
      detail: `Gateway is responsive (${responseTime}ms)`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      responseSmokeValidated: false,
      ...(warning ? { warning } : {}),
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Network errors, timeouts, etc.
    const isTimeout = errorMessage.includes('timeout') || errorMessage.includes('Timeout');
    const isNetwork = errorMessage.includes('fetch') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('ENOTFOUND');

    return {
      status: 'error',
      detail: `Gateway is unreachable: ${errorMessage}`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: false,
      remediation: isTimeout
        ? 'Gateway is slow or not responding. Check gateway health and network connectivity'
        : isNetwork
          ? 'Cannot reach gateway endpoint. Verify the URL is reachable and check network/firewall rules'
          : 'Unexpected error connecting to gateway. Check logs for details',
    };
  }
}

/**
 * Stage 2: Full response validation test
 * Tests model inference via /responses endpoint with the resolved gateway model
 * CONSUMES inference tokens - only call when explicitly requested
 *
 * @param gatewayUrl Base gateway URL (e.g., https://llmgateway.local.xyz/v1)
 * @param apiKey LLM gateway API key
 * @param timestamp ISO 8601 timestamp for the test
 * @param startTime Performance.now() from test start
 * @returns ResponseSmokeTestResult with inference details
 */
export async function testGatewayResponseSmoke_Stage2(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<ResponseSmokeTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, false);
}

async function testGatewayResponseSmokeFull(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
  legacyShape: boolean,
): Promise<ResponseSmokeTestResult & GatewayTestResult> {
  const checks: ResponseSmokeSubcheck[] = [];

  // For Cloudflare gateways, skip full smoke testing (Cloudflare only supports Chat Completions, not Responses API)
  // The health check to /models endpoint already validated connectivity and authentication
  if (isCloudflareGateway(gatewayUrl)) {
    const responseTime = performance.now() - startTime;
    checks.push({
      name: 'cloudflare-compat-note',
      status: 'ok',
      detail: 'Cloudflare gateway detected. Full response smoke test skipped (Cloudflare only supports Chat Completions). Stage 1 uses the scoped /compat/chat/completions probe.',
      responseTime,
    });
    return {
      status: 'ok',
      detail: 'Cloudflare gateway connectivity verified (health check passed via scoped /compat probe, full Responses smoke test not applicable)',
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      responseSmokeValidated: true, // Mark as validated since we did the health check
      checks,
    };
  }

  const jsonCheck = await runGatewayResponseJsonCheck(
    gatewayUrl,
    apiKey,
    timestamp,
    startTime,
    GATEWAY_RESPONSE_SMOKE_PROMPT,
    'json-response',
    legacyShape,
  );
  checks.push(jsonCheck.check);
  if (jsonCheck.result.status === 'error') {
    return { ...jsonCheck.result, checks };
  }

  const streamCheck = await runGatewayResponseStreamCheck(gatewayUrl, apiKey, timestamp, startTime);
  checks.push(streamCheck.check);
  if (streamCheck.result.status === 'error') {
    return { ...streamCheck.result, checks };
  }

  const largeCheck = await runGatewayResponseJsonCheck(
    gatewayUrl,
    apiKey,
    timestamp,
    startTime,
    GATEWAY_RESPONSE_LARGE_SMOKE_PROMPT,
    'large-prompt-response',
    legacyShape,
  );
  checks.push(largeCheck.check);
  if (largeCheck.result.status === 'error') {
    return { ...largeCheck.result, streamSmokeValidated: true, checks };
  }

  return {
    ...largeCheck.result,
    status: 'ok',
    detail: `Gateway Responses API smoke checks passed (${checks.length} checks)`,
    streamSmokeValidated: true,
    largePromptSmokeValidated: true,
    responseSmokeValidated: true,
    checks,
  };
}

async function runGatewayResponseJsonCheck(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
  prompt: string,
  checkName: 'json-response' | 'large-prompt-response',
  legacyShape: boolean,
): Promise<{ result: ResponseSmokeTestResult & GatewayTestResult; check: ResponseSmokeSubcheck }> {
  // Helper to extract response text
  const extractResponseText = (value: unknown): string => {
    if (!value || typeof value !== 'object') return '';
    const response = value as any;
    if (typeof response.output_text === 'string') return response.output_text;
    if (typeof response.text === 'string') return response.text;
    if (Array.isArray(response.output)) {
      return response.output.map((item: any) => {
        if (!item || typeof item !== 'object') return '';
        if (typeof item.text === 'string') return item.text;
        if (!Array.isArray(item.content)) return '';
        return item.content.map((part: any) => {
          if (!part || typeof part !== 'object') return '';
          if (typeof part.text === 'string') return part.text;
          if (typeof part.output_text === 'string') return part.output_text;
          return '';
        }).join('');
      }).join('');
    }
    return '';
  };

  const responseEndpoint = buildResponsesEndpoint(gatewayUrl);
  const fetchStartTime = performance.now();
  try {
    const response = await fetchWithTimeout(responseEndpoint, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: resolveGatewayModel(),
        input: prompt,
        max_output_tokens: GATEWAY_RESPONSE_SMOKE_MAX_OUTPUT_TOKENS,
      }),
    }, GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);
    const bodyText = await response.text();
    if (!response.ok) {
      const authError = response.status === 401 || response.status === 403;
      return {
        result: {
          status: 'error',
          detail: `Gateway ${checkName} smoke test returned HTTP ${response.status}: ${bodyText.substring(0, 160)}`,
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: !authError,
          responseSmokeValidated: false,
          httpStatus: response.status,
          remediation: authError
            ? 'Authentication failed for the Responses API smoke test. Check that LLM_GATEWAY_API_KEY is valid for response generation.'
            : 'Gateway /responses path is unhealthy or incompatible. Verify the gateway supports OpenAI Responses API requests with the resolved gateway model (default dynamic/kaseki-agent).',
        },
        check: { name: checkName, status: 'error', detail: `HTTP ${response.status}`, responseTime },
      };
    }

    let body: unknown;
    try {
      body = JSON.parse(bodyText);
    } catch {
      return {
        result: {
          status: 'error',
          detail: `Gateway ${checkName} smoke test returned non-JSON content: ${bodyText.substring(0, 160)}`,
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: true,
          responseSmokeValidated: false,
          remediation: 'Gateway /responses should return OpenAI Responses-compatible JSON for dynamic/kaseki-agent by default, or the resolved gateway model.',
        },
        check: { name: checkName, status: 'error', detail: 'non-JSON response body', responseTime },
      };
    }

    const text = extractResponseText(body);
    const outputTokens = extractOutputTokens(body);
    const responseId = typeof (body as any)?.id === 'string' ? (body as any).id : undefined;
    if (!text.trim()) {
      const detailParts = [
        'Gateway Responses API smoke test returned no assistant text.',
        responseId ? `response_id=${responseId}` : '',
        outputTokens !== undefined ? `output_tokens=${outputTokens}` : '',
      ].filter(Boolean);
      return {
        result: {
          status: 'error',
          detail: detailParts.join(' '),
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: true,
          responseSmokeValidated: false,
          responseId,
          outputTokens,
          remediation: 'Gateway accepted the resolved gateway model for routing but returned an empty assistant response. Keep dynamic/kaseki-agent enabled by default, or set KASEKI_MODEL/LLM_GATEWAY_MODEL to a supported model; fix the Responses API adapter to surface routed model output as output_text, response.output_text.delta, or assistant message content.',
        },
        check: { name: checkName, status: 'error', detail: detailParts.join(' '), responseTime, responseId, outputTokens },
      };
    }

    return {
      result: {
        status: 'ok',
        detail: `${checkName} generated valid response (${responseTime}ms)`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: true,
        responseSmokeValidated: legacyShape ? true : undefined,
        responseId,
        outputTokens,
        largePromptSmokeValidated: checkName === 'large-prompt-response' ? true : undefined,
      },
      check: { name: checkName, status: 'ok', detail: 'assistant text returned', responseTime, responseId, outputTokens },
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      result: {
        status: 'error',
        detail: `Gateway ${checkName} smoke test failed: ${errorMessage}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: false,
        responseSmokeValidated: false,
        remediation: 'Cannot complete a Responses API request with the resolved gateway model. Check gateway health, routing, and network access.',
      },
      check: { name: checkName, status: 'error', detail: errorMessage, responseTime },
    };
  }
}

async function runGatewayResponseStreamCheck(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<{ result: ResponseSmokeTestResult & GatewayTestResult; check: ResponseSmokeSubcheck }> {
  const responseEndpoint = buildResponsesEndpoint(gatewayUrl);
  const fetchStartTime = performance.now();
  try {
    const response = await fetchWithTimeout(responseEndpoint, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: 'text/event-stream',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: resolveGatewayModel(),
        input: GATEWAY_RESPONSE_SMOKE_PROMPT,
        max_output_tokens: GATEWAY_RESPONSE_SMOKE_MAX_OUTPUT_TOKENS,
        stream: true,
      }),
    }, GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);
    const bodyText = await response.text();
    if (!response.ok) {
      const authError = response.status === 401 || response.status === 403;
      return {
        result: {
          status: 'error',
          detail: `Gateway streaming smoke test returned HTTP ${response.status}: ${bodyText.substring(0, 160)}`,
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: !authError,
          responseSmokeValidated: false,
          streamSmokeValidated: false,
          httpStatus: response.status,
          remediation: authError
            ? 'Authentication failed for the streaming Responses API smoke test. Check that LLM_GATEWAY_API_KEY is valid for response generation.'
            : 'Gateway streaming /responses path is unhealthy or incompatible. Verify it emits OpenAI Responses SSE events for stream=true.',
        },
        check: { name: 'streaming-response', status: 'error', detail: `HTTP ${response.status}`, responseTime },
      };
    }

    const parsed = parseResponsesSse(bodyText);
    if (!parsed.text.trim()) {
      const detailParts = [
        'Gateway streaming smoke test returned no assistant text deltas.',
        parsed.responseId ? `response_id=${parsed.responseId}` : '',
        parsed.outputTokens !== undefined ? `output_tokens=${parsed.outputTokens}` : '',
      ].filter(Boolean);
      return {
        result: {
          status: 'error',
          detail: detailParts.join(' '),
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: true,
          responseSmokeValidated: false,
          streamSmokeValidated: false,
          responseId: parsed.responseId,
          outputTokens: parsed.outputTokens,
          remediation: 'Gateway accepted stream=true but produced no response.output_text.delta events and no final assistant text. Fix the Responses API streaming adapter before running Kaseki agent traffic through the resolved gateway model.',
        },
        check: {
          name: 'streaming-response',
          status: 'error',
          detail: detailParts.join(' '),
          responseTime,
          responseId: parsed.responseId,
          outputTokens: parsed.outputTokens,
        },
      };
    }

    return {
      result: {
        status: 'ok',
        detail: `streaming-response generated valid deltas (${responseTime}ms)`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: true,
        responseSmokeValidated: true,
        streamSmokeValidated: true,
        responseId: parsed.responseId,
        outputTokens: parsed.outputTokens,
      },
      check: {
        name: 'streaming-response',
        status: 'ok',
        detail: 'assistant text deltas returned',
        responseTime,
        responseId: parsed.responseId,
        outputTokens: parsed.outputTokens,
      },
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      result: {
        status: 'error',
        detail: `Gateway streaming smoke test failed: ${errorMessage}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: false,
        responseSmokeValidated: false,
        streamSmokeValidated: false,
        remediation: 'Cannot complete a stream=true Responses API request with the resolved gateway model. Check gateway health, routing, and SSE adapter behavior.',
      },
      check: { name: 'streaming-response', status: 'error', detail: errorMessage, responseTime },
    };
  }
}

async function testGatewayResponseSmoke(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<GatewayTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, true);
}

// Re-export builder functions from detection module for backward compatibility
export {
  isCloudflareGateway,
  buildModelsEndpoint,
  buildResponsesEndpoint,
  buildCloudflareInferenceEndpoint,
} from './gateway-detection/detect-gateway-provider';

// Re-export analysis functions from validation module
export { extractSampleEventStructure, analyzeResponseStructure } from './gateway-validation/analyze-gateway-response';
export { extractPiJsonAssistantText } from './gateway-validation/extract-pi-json';

// Re-export from detection module for backward compatibility
export { isResponsesEndpoint } from './gateway-detection/detect-gateway-provider';

// Re-export from extraction module for backward compatibility
export { formatGatewayTestResponse } from './gateway-validation/extract-pi-json';
