import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import {
  resolveGatewayApiKey,
  shouldRunGatewayResponseSmoke,
  shouldRunPiProviderSmoke,
  resolveGatewayModel,
  isCloudflareGateway,
  buildStage1ProbeRequest,
  isResponsesEndpoint,
  isInvalidGatewayPathError,
  type GatewayTestOptions,
} from './gateway-detection/detect-gateway-provider';
import {
  analyzeResponseStructure,
  extractSampleEventStructure,
  countPiJsonEvents,
} from './gateway-validation/analyze-gateway-response';
import {
  extractPiJsonAssistantText,
  fetchWithTimeout,
} from './gateway-validation/extract-pi-json';
import {
  testGatewayResponseSmokeFull,
} from './gateway-validation/gateway-response-smoke-checks';

/**
 * LLM Gateway Responsiveness Test
 *
 * Validates that the configured LLM gateway is:
 * 1. Reachable (network connectivity)
 * 2. Responsive (returns HTTP responses)
 * 3. Authenticated (API key is accepted)
 *
 * This is a lightweight test for standard gateways; Cloudflare /compat gateways require
 * a minimal chat-completions probe because they do not expose an unscoped /models route.
 */

/**
 * Stage 1: Lightweight connectivity test result (reachability + authentication)
 * Tests /models endpoint to validate gateway is up and API key works. Cloudflare /compat
 * gateways use a minimal chat-completions probe because /v1/models is not valid there.
 */
export interface ConnectivityTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Gateway is responsive (1234ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /models request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /models endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /models endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
}

/**
 * Stage 2: Full response validation test result (model inference smoke test)
 * Tests /responses endpoint with the resolved gateway model to validate inference
 * CONSUMES inference tokens - only run when explicitly triggered
 */
export interface ResponseSmokeTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Model generated valid response (9586ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /responses request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /responses endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /responses endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
  responseId?: string; // Response ID from gateway (e.g., "resp_xyz")
  outputTokens?: number; // Tokens generated by model
  modelUsed?: string; // Which model handled the request (if available)
  streamSmokeValidated?: boolean; // Streaming Responses API produced deltas or final assistant text
  largePromptSmokeValidated?: boolean; // Larger agent-shaped prompt produced assistant text
  checks?: ResponseSmokeSubcheck[]; // Per-contract smoke diagnostics
}

export interface ResponseSmokeSubcheck {
  name: 'json-response' | 'streaming-response' | 'large-prompt-response' | 'pi-provider-response' | 'cloudflare-compat-note';
  status: 'ok' | 'error';
  detail: string;
  responseTime: number;
  responseId?: string;
  outputTokens?: number;
}

export interface PiProviderSmokeTestResult {
  status: 'ok' | 'error' | 'skipped';
  detail: string;
  responseTime: number;
  timestamp: string;
  provider: 'gateway';
  model: string;
  outputEventCount?: number;
  assistantTextChars?: number;
  codingShapeValidated?: boolean;
  toolCallCount?: number;
  turnCount?: number;
  multiTurnValidated?: boolean;
  exitCode?: number | null;
  remediation?: string;
  diagnostics?: {
    fieldsSearched?: string[];
    fieldsFound?: string[];
    eventsByType?: Record<string, number>;
    eventsWithText?: number;
    assistantEventsWithText?: number;
    nonAssistantEventsWithText?: number;
    assistantFieldsFound?: string[];
    nonAssistantFieldsFound?: string[];
    suggestedPatterns?: string[];
    sampleEventStructure?: any;
    debugOutputPath?: string;
    rawAssistantPreview?: string;
  };
}

/**
 * Orchestrated full test result (stage 1 + stage 2)
 * Combines both stages with metadata about why stage 2 was skipped/run
 */
export interface FullGatewayTestResult {
  stage1: ConnectivityTestResult;
  stage2?: ResponseSmokeTestResult; // Only present if stage 2 ran
  orchestrationMetadata: {
    skippedStage2Reason?: string; // e.g., "Development environment", "Token consumption not desired"
    stage2Requested?: boolean; // Was stage 2 explicitly requested via options or query param?
    environmentDetected: string; // e.g., "production", "development", "test"
  };
}

/**
 * @deprecated Use ConnectivityTestResult or ResponseSmokeTestResult instead
 * Legacy result type for backward compatibility
 */
export interface GatewayTestResult {
  status: 'ok' | 'error';
  detail: string;
  gatewayUrl?: string;
  responseTime: number; // milliseconds
  timestamp: string; // ISO 8601
  authenticationValidated: boolean;
  remediation?: string;
  httpStatus?: number;
  warning?: string;
  responseSmokeValidated?: boolean;
  responseId?: string;
  outputTokens?: number;
}

const GATEWAY_LATENCY_WARNING_MS = 5000;
// Timeout for /models endpoint (lightweight check)
const GATEWAY_MODELS_TIMEOUT_MS = 10000;
const PI_PROVIDER_SMOKE_TIMEOUT_MS = (() => {
  const envValue = process.env.KASEKI_PI_PROVIDER_SMOKE_TIMEOUT_MS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  return 60000;
})();

// Re-export GatewayApiKeyResolution and GatewayTestOptions from detection module for backward compatibility
export type { GatewayApiKeyResolution, GatewayTestOptions } from './gateway-detection/detect-gateway-provider';
export { resolveGatewayApiKey, detectGatewayTestEnvironment, shouldRunGatewayResponseSmoke, shouldRunPiProviderSmoke, resolveGatewayModel } from './gateway-detection/detect-gateway-provider';

/**
 * Options for Pi provider smoke test
 */
export interface PiProviderSmokeTestOptions {
  requested?: boolean;
  debug?: boolean; // Log full response and diagnostics
}

/**
 * Verify Pi provider is registered and configured correctly
 */
export function verifyPiProviderRegistration(): {
  registered: boolean;
  apiType?: string;
  model?: string;
  baseUrl?: string;
  issues?: string[];
  } {
  const result: any = {
    registered: false,
    issues: [],
  };

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const model = resolveGatewayModel();

  if (!gatewayUrl) {
    result.issues.push('LLM_GATEWAY_URL not configured');
  }

  if (!process.env.LLM_GATEWAY_API_KEY && !process.env.LLM_GATEWAY_API_KEY_FILE) {
    result.issues.push('LLM_GATEWAY_API_KEY or LLM_GATEWAY_API_KEY_FILE not configured');
  }

  result.registered = result.issues.length === 0;
  result.apiType = isCloudflareGateway(gatewayUrl ?? '') ? 'openai-completions' : 'openai-responses';
  result.model = model;
  result.baseUrl = gatewayUrl;

  return result;
}

export function testPiGatewayProviderSmoke(requested: boolean | PiProviderSmokeTestOptions = false): PiProviderSmokeTestResult {
  const timestamp = new Date().toISOString();
  const startTime = performance.now();
  const model = resolveGatewayModel();

  // Handle both boolean (backward compat) and options object
  const options: PiProviderSmokeTestOptions = typeof requested === 'object' ? requested : { requested };
  const debugMode = options.debug === true;
  const requestedSmoke = options.requested === true;

  if (!shouldRunPiProviderSmoke(requestedSmoke)) {
    const remediation = 'Pi provider smoke is opt-in because it can consume gateway tokens. Add ?piProvider=true to the request, or set KASEKI_ALLOW_DEV_PI_PROVIDER_SMOKE=1 to enable for integration testing.';

    return {
      status: 'skipped',
      detail: 'Pi provider smoke skipped. It requires opt-in to conserve LLM gateway tokens.',
      responseTime: 0,
      timestamp,
      provider: 'gateway',
      model,
      remediation,
    };
  }

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;
  if (!gatewayUrl || !apiKey) {
    return {
      status: 'error',
      detail: 'Pi provider smoke cannot run because LLM_GATEWAY_URL or LLM_GATEWAY_API_KEY is missing',
      responseTime: 0,
      timestamp,
      provider: 'gateway',
      model,
      remediation: 'Configure gateway URL and API key before running Pi provider smoke.',
    };
  }

  const prompt = [
    'You are the coding phase of an ephemeral repository agent.',
    'Synthetic task: inspect package.json and propose one concise documentation improvement.',
    'You must use the read tool to inspect package.json before answering. Do not modify files.',
    'This validates streamed tool calls and a subsequent assistant turn through the gateway.',
    'Return exactly one JSON object and no markdown:',
    '{"status":"ok","phase":"coding","changed_files":[],"summary":"kaseki pi provider smoke ok"}',
  ].join('\n');
  const child = spawnSync('pi', ['--mode', 'json', '--no-session', '--provider', 'gateway', '--model', model, prompt], {
    encoding: 'utf8',
    timeout: PI_PROVIDER_SMOKE_TIMEOUT_MS,
    env: {
      ...process.env,
      LLM_GATEWAY_URL: gatewayUrl,
      LLM_GATEWAY_API_KEY: apiKey,
      LLM_GATEWAY_MAX_OUTPUT_TOKENS: '128',
    },
    // Pi JSON mode can emit cumulative message snapshots and provider metadata
    // well beyond Node's small default buffer even for this constrained prompt.
    // Keep the smoke bounded, but large enough to distinguish adapter failures
    // from child_process ENOBUFS transport failures.
    maxBuffer: 16 * 1024 * 1024,
  });
  const responseTime = Math.round(performance.now() - startTime);
  const stdout = child.stdout || '';
  const stderr = child.stderr || '';
  const assistantText = extractPiJsonAssistantText(stdout);
  const responseAnalysis = analyzeResponseStructure(stdout);
  const toolCallCount = responseAnalysis.eventsByType.tool_execution_start || 0;
  const turnCount = responseAnalysis.eventsByType.turn_start || 0;
  const multiTurnValidated = toolCallCount > 0 && turnCount >= 2;

  if (child.error) {
    const timedOut = child.error.message.includes('ETIMEDOUT');
    const outputOverflow = child.error.message.includes('ENOBUFS');
    return {
      status: 'error',
      detail: `Pi provider smoke failed to start or complete: ${child.error.message}`,
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      remediation: timedOut
        ? 'Pi provider smoke timed out. Check gateway latency and Pi provider registration.'
        : outputOverflow
          ? 'Pi produced excessive JSONL output during the smoke test. Inspect provider event amplification and keep cumulative event payloads bounded.'
          : child.error.message.includes('ENOENT')
            ? 'Check that Pi CLI is installed in the controller image.'
            : 'Check that the gateway provider extension loads and inspect the Pi adapter diagnostics.',
    };
  }

  if (child.status !== 0) {
    return {
      status: 'error',
      detail: `Pi provider smoke exited ${child.status}: ${(stderr || stdout).slice(0, 240)}`,
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      remediation: 'Gateway HTTP smoke can pass while Pi provider registration fails. Check .gateway-diagnostics.jsonl and provider api type.',
    };
  }

  if (!assistantText.trim()) {
    const analysis = responseAnalysis;
    const sampleEvent = extractSampleEventStructure(stdout);

    let debugOutputPath: string | undefined;
    if (debugMode) {
      // In debug mode, persist raw response for diagnostics.
      try {
        const debugPath = `/tmp/kaseki-pi-debug-${Date.now()}.jsonl`;
        fs.writeFileSync(debugPath, stdout);
        debugOutputPath = debugPath;
      } catch {
        // Ignore write errors in debug mode
      }
    }

    return {
      status: 'error',
      detail: 'Pi provider smoke completed but produced no assistant text',
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      outputEventCount: countPiJsonEvents(stdout),
      assistantTextChars: 0,
      diagnostics: {
        fieldsSearched: [
          'message.text',
          'message.output_text',
          'message.assistantMessage',
          'message.content (string)',
          'message.choices[0].message.content',
          'message.choices[0].delta.content',
          'message.response.content',
        ],
        fieldsFound: analysis.fieldsFound,
        eventsByType: analysis.eventsByType,
        eventsWithText: analysis.eventsWithText,
        assistantEventsWithText: analysis.assistantEventsWithText,
        nonAssistantEventsWithText: analysis.nonAssistantEventsWithText,
        assistantFieldsFound: analysis.assistantFieldsFound,
        nonAssistantFieldsFound: analysis.nonAssistantFieldsFound,
        suggestedPatterns: analysis.suggestedPatterns,
        sampleEventStructure: sampleEvent,
        ...(debugOutputPath ? { debugOutputPath } : {}),
      },
      remediation:
        analysis.suggestedPatterns.length > 0
          ? `Found assistant response fields but text not extracted. Try patterns: ${analysis.suggestedPatterns.slice(0, 2).join(', ')}. Check Pi provider registration and gateway response format.`
          : analysis.nonAssistantFieldsFound.length > 0
            ? `Found text fields only on non-assistant messages (${analysis.nonAssistantFieldsFound.slice(0, 2).join(', ')}), but no assistant text was produced. Verify Pi provider api uses openai-responses and gateway assistant output is streamed with role=assistant.`
            : 'No assistant response fields found. Verify Pi provider api uses openai-responses and gateway is returning valid assistant responses.',
    };
  }

  let codingShapeValidated = false;
  try {
    const smokePayload = JSON.parse(assistantText.trim()) as Record<string, unknown>;
    codingShapeValidated = smokePayload.status === 'ok' && smokePayload.phase === 'coding' && multiTurnValidated;
  } catch {
    codingShapeValidated = false;
  }
  if (!codingShapeValidated) {
    let debugOutputPath: string | undefined;
    try {
      const diagnosticsDir = process.env.KASEKI_RESULTS_DIR || '/tmp';
      fs.mkdirSync(diagnosticsDir, { recursive: true });
      debugOutputPath = `${diagnosticsDir}/pi-provider-smoke-failed-${Date.now()}.jsonl`;
      fs.writeFileSync(debugOutputPath, stdout, { mode: 0o600 });
    } catch {
      debugOutputPath = undefined;
    }
    return {
      status: 'error',
      detail: 'Pi provider produced assistant text but did not satisfy the coding-shaped JSON contract',
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      outputEventCount: countPiJsonEvents(stdout),
      assistantTextChars: assistantText.trim().length,
      codingShapeValidated: false,
      toolCallCount,
      turnCount,
      multiTurnValidated,
      diagnostics: {
        ...(debugOutputPath ? { debugOutputPath } : {}),
        rawAssistantPreview: assistantText.trim().slice(0, 1000),
      },
      remediation: multiTurnValidated
        ? 'Inspect the gateway response body and Pi event stream; the multi-turn tool flow passed but the final coding contract failed.'
        : 'The gateway must sustain a streamed tool call and follow-up assistant turn. Inspect tool-call deltas, finish reasons, and adapter stream handling.',
    };
  }

  return {
    status: 'ok',
    detail: `Pi gateway provider produced assistant text (${responseTime}ms)`,
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    outputEventCount: countPiJsonEvents(stdout),
    assistantTextChars: assistantText.trim().length,
    codingShapeValidated,
    toolCallCount,
    turnCount,
    multiTurnValidated,
  };
}

/**
 * Stage 1: Lightweight gateway connectivity test
 * Tests reachability and authentication via /models endpoint
 * Does NOT consume inference tokens
 *
 * @returns ConnectivityTestResult with status and diagnostics
 */
export async function testGatewayConnectivity_Stage1(): Promise<ConnectivityTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();

  // Check configuration
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_URL is not configured',
      gatewayUrl: '',
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
    };
  }

  if (!apiKey) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_API_KEY is not configured',
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
    };
  }

  // Validate URL format
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      status: 'error',
      detail: `Gateway URL is invalid: ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      status: 'error',
      detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
    };
  }

  // Make test request to the appropriate Stage 1 probe endpoint. Standard
  // OpenAI-compatible gateways can use /models; Cloudflare /compat gateways must
  // preserve the scoped /v1/{account_id}/{gateway_id}/compat path and probe chat completions.
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  try {
    const fetchStartTime = performance.now();
    const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);

    if (!response.ok) {
      const errorBody = await response.text();
      const authError = response.status === 401 || response.status === 403;
      const invalidPathError = isInvalidGatewayPathError(errorBody);

      return {
        status: 'error',
        detail: `Gateway returned HTTP ${response.status}: ${errorBody.substring(0, 100)}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: !authError && !invalidPathError,
        httpStatus: response.status,
        remediation: authError
          ? 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token'
          : invalidPathError
            ? 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.'
            : `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${response.status})`,
      };
    }

    // Successful response
    const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
      ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
      : undefined;
    return {
      status: 'ok',
      detail: `Gateway is responsive (${responseTime}ms)`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      ...(warning ? { warning } : {}),
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Network errors, timeouts, etc.
    const isTimeout = errorMessage.includes('timeout') || errorMessage.includes('Timeout');
    const isNetwork = errorMessage.includes('fetch') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('ENOTFOUND');

    return {
      status: 'error',
      detail: `Gateway is unreachable: ${errorMessage}`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: false,
      remediation: isTimeout
        ? 'Gateway is slow or not responding. Check gateway health and network connectivity'
        : isNetwork
          ? 'Cannot reach gateway endpoint. Verify the URL is reachable and check network/firewall rules'
          : 'Unexpected error connecting to gateway. Check logs for details',
    };
  }
}

/**
 * Test LLM gateway responsiveness
 *
 * @returns Gateway test result with status and diagnostics
 */
export async function testGatewayConnectivity(options: GatewayTestOptions = {}): Promise<GatewayTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();

  // Check configuration
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_URL is not configured',
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
    };
  }

  if (!apiKey) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_API_KEY is not configured',
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
    };
  }

  // Validate URL format
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      status: 'error',
      detail: `Gateway URL is invalid: ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      status: 'error',
      detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
    };
  }

  // Make test request to the appropriate Stage 1 probe endpoint. Standard
  // OpenAI-compatible gateways can use /models; Cloudflare /compat gateways must
  // preserve the scoped /v1/{account_id}/{gateway_id}/compat path and probe chat completions.
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  try {
    const fetchStartTime = performance.now();
    const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);

    if (!response.ok) {
      const errorBody = await response.text();
      const authError = response.status === 401 || response.status === 403;
      const invalidPathError = isInvalidGatewayPathError(errorBody);

      return {
        status: 'error',
        detail: `Gateway returned HTTP ${response.status}: ${errorBody.substring(0, 100)}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: !authError && !invalidPathError,
        httpStatus: response.status,
        remediation: authError
          ? 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token'
          : invalidPathError
            ? 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.'
            : `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${response.status})`,
      };
    }

    if (shouldRunGatewayResponseSmoke(options)) {
      const smokeResult = await testGatewayResponseSmoke(gatewayUrl, apiKey, timestamp, startTime);
      if (smokeResult.status === 'error') return smokeResult;

      const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
        ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
        : undefined;
      return {
        ...smokeResult,
        detail: `Gateway is responsive and returned usable Responses API content (${smokeResult.responseTime}ms)`,
        warning,
      };
    }

    // Successful response
    const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
      ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
      : undefined;
    return {
      status: 'ok',
      detail: `Gateway is responsive (${responseTime}ms)`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      responseSmokeValidated: false,
      ...(warning ? { warning } : {}),
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Network errors, timeouts, etc.
    const isTimeout = errorMessage.includes('timeout') || errorMessage.includes('Timeout');
    const isNetwork = errorMessage.includes('fetch') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('ENOTFOUND');

    return {
      status: 'error',
      detail: `Gateway is unreachable: ${errorMessage}`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: false,
      remediation: isTimeout
        ? 'Gateway is slow or not responding. Check gateway health and network connectivity'
        : isNetwork
          ? 'Cannot reach gateway endpoint. Verify the URL is reachable and check network/firewall rules'
          : 'Unexpected error connecting to gateway. Check logs for details',
    };
  }
}

/**
 * Stage 2: Full response validation test
 * Tests model inference via /responses endpoint with the resolved gateway model
 * CONSUMES inference tokens - only call when explicitly requested
 *
 * @param gatewayUrl Base gateway URL (e.g., https://llmgateway.local.xyz/v1)
 * @param apiKey LLM gateway API key
 * @param timestamp ISO 8601 timestamp for the test
 * @param startTime Performance.now() from test start
 * @returns ResponseSmokeTestResult with inference details
 */
export async function testGatewayResponseSmoke_Stage2(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<ResponseSmokeTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, false);
}

async function testGatewayResponseSmoke(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<GatewayTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, true);
}

// Re-export builder functions from detection module for backward compatibility
export {
  isCloudflareGateway,
  buildModelsEndpoint,
  buildResponsesEndpoint,
  buildCloudflareInferenceEndpoint,
} from './gateway-detection/detect-gateway-provider';

// Re-export analysis functions from validation module
export { extractSampleEventStructure, analyzeResponseStructure } from './gateway-validation/analyze-gateway-response';
export { extractPiJsonAssistantText } from './gateway-validation/extract-pi-json';

// Re-export from detection module for backward compatibility
export { isResponsesEndpoint } from './gateway-detection/detect-gateway-provider';

// Re-export from extraction module for backward compatibility
export { formatGatewayTestResponse } from './gateway-validation/extract-pi-json';
