import { readHostSecret } from './secrets/host-secrets-reader';
import { spawnSync } from 'node:child_process';

/**
 * LLM Gateway Responsiveness Test
 *
 * Validates that the configured LLM gateway is:
 * 1. Reachable (network connectivity)
 * 2. Responsive (returns HTTP responses)
 * 3. Authenticated (API key is accepted)
 *
 * This is a lightweight test for standard gateways; Cloudflare /compat gateways require
 * a minimal chat-completions probe because they do not expose an unscoped /models route.
 */

/**
 * Stage 1: Lightweight connectivity test result (reachability + authentication)
 * Tests /models endpoint to validate gateway is up and API key works. Cloudflare /compat
 * gateways use a minimal chat-completions probe because /v1/models is not valid there.
 */
export interface ConnectivityTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Gateway is responsive (1234ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /models request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /models endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /models endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
}

/**
 * Stage 2: Full response validation test result (model inference smoke test)
 * Tests /responses endpoint with the resolved gateway model to validate inference
 * CONSUMES inference tokens - only run in production or when explicitly triggered
 */
export interface ResponseSmokeTestResult {
  status: 'ok' | 'error';
  detail: string; // e.g., "Model generated valid response (9586ms)"
  gatewayUrl: string;
  responseTime: number; // milliseconds for /responses request
  timestamp: string; // ISO 8601
  authenticationValidated: boolean; // API key accepted by /responses endpoint
  remediation?: string; // Error recovery steps
  httpStatus?: number; // HTTP status from /responses endpoint
  warning?: string; // Non-fatal issues (e.g., slow response)
  responseId?: string; // Response ID from gateway (e.g., "resp_xyz")
  outputTokens?: number; // Tokens generated by model
  modelUsed?: string; // Which model handled the request (if available)
  streamSmokeValidated?: boolean; // Streaming Responses API produced deltas or final assistant text
  largePromptSmokeValidated?: boolean; // Larger agent-shaped prompt produced assistant text
  checks?: ResponseSmokeSubcheck[]; // Per-contract smoke diagnostics
}

export interface ResponseSmokeSubcheck {
  name: 'json-response' | 'streaming-response' | 'large-prompt-response' | 'pi-provider-response' | 'cloudflare-compat-note';
  status: 'ok' | 'error';
  detail: string;
  responseTime: number;
  responseId?: string;
  outputTokens?: number;
}

export interface PiProviderSmokeTestResult {
  status: 'ok' | 'error' | 'skipped';
  detail: string;
  responseTime: number;
  timestamp: string;
  provider: 'gateway';
  model: string;
  outputEventCount?: number;
  assistantTextChars?: number;
  exitCode?: number | null;
  remediation?: string;
  diagnostics?: {
    fieldsSearched?: string[];
    fieldsFound?: string[];
    eventsByType?: Record<string, number>;
    eventsWithText?: number;
    suggestedPatterns?: string[];
    sampleEventStructure?: any;
  };
}

/**
 * Orchestrated full test result (stage 1 + stage 2)
 * Combines both stages with metadata about why stage 2 was skipped/run
 */
export interface FullGatewayTestResult {
  stage1: ConnectivityTestResult;
  stage2?: ResponseSmokeTestResult; // Only present if stage 2 ran
  orchestrationMetadata: {
    skippedStage2Reason?: string; // e.g., "Development environment", "Token consumption not desired"
    stage2Requested?: boolean; // Was stage 2 explicitly requested via options or query param?
    environmentDetected: string; // e.g., "production", "development", "test"
  };
}

/**
 * @deprecated Use ConnectivityTestResult or ResponseSmokeTestResult instead
 * Legacy result type for backward compatibility
 */
export interface GatewayTestResult {
  status: 'ok' | 'error';
  detail: string;
  gatewayUrl?: string;
  responseTime: number; // milliseconds
  timestamp: string; // ISO 8601
  authenticationValidated: boolean;
  remediation?: string;
  httpStatus?: number;
  warning?: string;
  responseSmokeValidated?: boolean;
  responseId?: string;
  outputTokens?: number;
}

export interface GatewayTestOptions {
  responseSmoke?: boolean;
  forceStage2?: boolean; // Force stage 2 to run even in dev/test environments
}

const GATEWAY_LATENCY_WARNING_MS = 5000;
// Accept base URLs (/v1), full response paths (/v1/responses), and gateway-specific suffixes (e.g., /v1/compat)
// For Cloudflare and similar gateways, allows /v1/{segments}/compat (e.g., /v1/account/namespace/compat)
// Pi CLI automatically appends /responses, so either format is valid
// Does NOT allow arbitrary endpoints like /v1/chat/completions
const GATEWAY_VALID_PATH_PATTERN = /\/v\d+(?:(?:\/[a-z0-9-]+)*\/compat)?(?:\/responses)?\/?$/;
// Timeout for /models endpoint (lightweight check)
const GATEWAY_MODELS_TIMEOUT_MS = 10000;
// Timeout for /responses endpoint (includes model inference)
// Default 45s allows for model selection, routing, and inference
const GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS = (() => {
  const envValue = process.env.KASEKI_GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  return 45000; // 45 second default
})();
const GATEWAY_RESPONSE_SMOKE_PROMPT = [
  'You are validating an OpenAI Responses API gateway for Kaseki agent prompts.',
  'Return exactly one JSON object with no markdown and no surrounding text.',
  'The JSON object must be: {"status":"ok","summary":"kaseki gateway smoke ok"}',
].join('\n');
const GATEWAY_RESPONSE_LARGE_SMOKE_PROMPT = [
  GATEWAY_RESPONSE_SMOKE_PROMPT,
  '',
  'Context sample:',
  ...Array.from({ length: 80 }, (_, index) =>
    `- file_${String(index + 1).padStart(2, '0')}.ts: inspect this synthetic repository note and preserve the required JSON-only response contract.`,
  ),
].join('\n');
const GATEWAY_RESPONSE_SMOKE_MAX_OUTPUT_TOKENS = 256;
const CLOUDFLARE_STAGE1_PROBE_PROMPT = 'Reply with ok.';
const PI_PROVIDER_SMOKE_TIMEOUT_MS = (() => {
  const envValue = process.env.KASEKI_PI_PROVIDER_SMOKE_TIMEOUT_MS;
  if (envValue) {
    const parsed = parseInt(envValue, 10);
    if (!isNaN(parsed) && parsed > 0) return parsed;
  }
  return 60000;
})();

export interface GatewayApiKeyResolution {
  configured: boolean;
  source: 'env' | 'host-secret' | 'missing';
  value?: string;
}

export function resolveGatewayApiKey(): GatewayApiKeyResolution {
  if (process.env.LLM_GATEWAY_API_KEY) {
    return {
      configured: true,
      source: 'env',
      value: process.env.LLM_GATEWAY_API_KEY,
    };
  }

  const hostSecret = readHostSecret('llm_gateway_api_key');
  if (hostSecret) {
    return {
      configured: true,
      source: 'host-secret',
      value: hostSecret,
    };
  }

  return {
    configured: false,
    source: 'missing',
  };
}

function parseBooleanOverride(value: unknown): boolean | undefined {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim().toLowerCase();
  if (['1', 'true', 'on', 'yes'].includes(normalized)) return true;
  if (['0', 'false', 'off', 'no'].includes(normalized)) return false;
  return undefined;
}

/**
 * Detect current environment for stage 2 token consumption decisions
 * Returns 'production' | 'development' | 'test'
 */
export function detectGatewayTestEnvironment(): 'production' | 'development' | 'test' {
  // Test environment: Jest runner
  if (process.env.JEST_WORKER_ID) return 'test';

  // Test/development environment: NODE_ENV
  if (process.env.NODE_ENV === 'test') return 'test';
  if (process.env.NODE_ENV === 'development') return 'development';

  // Development environment: KASEKI_ENV
  if (process.env.KASEKI_ENV === 'development') return 'development';

  // Default to production for safety
  return 'production';
}

export function shouldRunGatewayResponseSmoke(options: GatewayTestOptions = {}): boolean {
  // 1. Explicit query param override (highest priority)
  if (typeof options.responseSmoke === 'boolean') return options.responseSmoke;

  // 2. Environment variable override
  const envOverride = parseBooleanOverride(process.env.KASEKI_GATEWAY_RESPONSE_SMOKE);
  if (typeof envOverride === 'boolean') return envOverride;

  // 3. Forced stage 2 for testing in dev/test environments
  if (options.forceStage2) return true;

  // 4. Environment-based default: only run stage 2 in production
  const environment = detectGatewayTestEnvironment();
  return environment === 'production';
}

export function shouldRunPiProviderSmoke(requested: boolean): boolean {
  const environment = detectGatewayTestEnvironment();

  // 1. Auto-run in production (no opt-in required)
  if (environment === 'production') return true;

  // 2. Allow explicit opt-in in any environment (requested=true from ?piProvider=true)
  if (requested) return true;

  // 3. Allow override via env var in non-production environments
  if (parseBooleanOverride(process.env.KASEKI_ALLOW_DEV_PI_PROVIDER_SMOKE) === true) return true;

  // 4. Default to skip in non-production without opt-in
  return false;
}

export function resolveGatewayModel(): string {
  return process.env.KASEKI_MODEL || process.env.LLM_GATEWAY_MODEL || 'dynamic/kaseki-agent';
}

export function testPiGatewayProviderSmoke(requested: boolean): PiProviderSmokeTestResult {
  const timestamp = new Date().toISOString();
  const startTime = performance.now();
  const model = resolveGatewayModel();

  if (!shouldRunPiProviderSmoke(requested)) {
    const environment = detectGatewayTestEnvironment();
    const remediation = environment === 'production'
      ? 'This should not happen in production (auto-run enabled). Check logs for errors.'
      : 'Pi provider smoke is opt-in in non-production environments. Add ?piProvider=true to the request, or set KASEKI_ALLOW_DEV_PI_PROVIDER_SMOKE=1 to enable for development testing.';

    return {
      status: 'skipped',
      detail: 'Pi provider smoke skipped. It runs by default in production, but requires opt-in in non-production environments to conserve LLM gateway tokens.',
      responseTime: 0,
      timestamp,
      provider: 'gateway',
      model,
      remediation,
    };
  }

  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;
  if (!gatewayUrl || !apiKey) {
    return {
      status: 'error',
      detail: 'Pi provider smoke cannot run because LLM_GATEWAY_URL or LLM_GATEWAY_API_KEY is missing',
      responseTime: 0,
      timestamp,
      provider: 'gateway',
      model,
      remediation: 'Configure gateway URL and API key before running Pi provider smoke.',
    };
  }

  const prompt = [
    'Return exactly this plain text and nothing else:',
    'kaseki pi provider smoke ok',
  ].join('\n');
  const child = spawnSync('pi', ['--mode', 'json', '--no-session', '--provider', 'gateway', '--model', model, prompt], {
    encoding: 'utf8',
    timeout: PI_PROVIDER_SMOKE_TIMEOUT_MS,
    env: {
      ...process.env,
      LLM_GATEWAY_URL: gatewayUrl,
      LLM_GATEWAY_API_KEY: apiKey,
      LLM_GATEWAY_MAX_OUTPUT_TOKENS: '128',
    },
    maxBuffer: 1024 * 1024,
  });
  const responseTime = Math.round(performance.now() - startTime);
  const stdout = child.stdout || '';
  const stderr = child.stderr || '';
  const assistantText = extractPiJsonAssistantText(stdout);

  if (child.error) {
    const timedOut = child.error.message.includes('ETIMEDOUT');
    return {
      status: 'error',
      detail: `Pi provider smoke failed to start or complete: ${child.error.message}`,
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      remediation: timedOut
        ? 'Pi provider smoke timed out. Check gateway latency and Pi provider registration.'
        : 'Check that Pi CLI is installed in the controller/worker image and gateway provider extension loads.',
    };
  }

  if (child.status !== 0) {
    return {
      status: 'error',
      detail: `Pi provider smoke exited ${child.status}: ${(stderr || stdout).slice(0, 240)}`,
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      remediation: 'Gateway HTTP smoke can pass while Pi provider registration fails. Check .gateway-diagnostics.jsonl and provider api type.',
    };
  }

  if (!assistantText.trim()) {
    const analysis = analyzeResponseStructure(stdout);
    const sampleEvent = extractSampleEventStructure(stdout);
    return {
      status: 'error',
      detail: 'Pi provider smoke completed but produced no assistant text',
      responseTime,
      timestamp,
      provider: 'gateway',
      model,
      exitCode: child.status,
      outputEventCount: countPiJsonEvents(stdout),
      assistantTextChars: 0,
      diagnostics: {
        fieldsSearched: [
          'message.text',
          'message.output_text',
          'message.assistantMessage',
          'message.content (string)',
          'message.choices[0].message.content',
          'message.choices[0].delta.content',
          'message.response.content',
        ],
        fieldsFound: analysis.fieldsFound,
        eventsByType: analysis.eventsByType,
        eventsWithText: analysis.eventsWithText,
        suggestedPatterns: analysis.suggestedPatterns,
        sampleEventStructure: sampleEvent,
      },
      remediation:
        analysis.suggestedPatterns.length > 0
          ? `Found response fields but text not extracted. Try patterns: ${analysis.suggestedPatterns.slice(0, 2).join(', ')}. Check Pi provider registration and gateway response format.`
          : 'No response fields found. Verify Pi provider api uses openai-responses and gateway is returning valid responses.',
    };
  }

  return {
    status: 'ok',
    detail: `Pi gateway provider produced assistant text (${responseTime}ms)`,
    responseTime,
    timestamp,
    provider: 'gateway',
    model,
    exitCode: child.status,
    outputEventCount: countPiJsonEvents(stdout),
    assistantTextChars: assistantText.trim().length,
  };
}

/**
 * Stage 1: Lightweight gateway connectivity test
 * Tests reachability and authentication via /models endpoint
 * Does NOT consume inference tokens
 *
 * @returns ConnectivityTestResult with status and diagnostics
 */
export async function testGatewayConnectivity_Stage1(): Promise<ConnectivityTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();

  // Check configuration
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_URL is not configured',
      gatewayUrl: '',
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
    };
  }

  if (!apiKey) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_API_KEY is not configured',
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
    };
  }

  // Validate URL format
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      status: 'error',
      detail: `Gateway URL is invalid: ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      status: 'error',
      detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
    };
  }

  // Make test request to the appropriate Stage 1 probe endpoint. Standard
  // OpenAI-compatible gateways can use /models; Cloudflare /compat gateways must
  // preserve the scoped /v1/{account_id}/{gateway_id}/compat path and probe chat completions.
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  try {
    const fetchStartTime = performance.now();
    const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);

    if (!response.ok) {
      const errorBody = await response.text();
      const authError = response.status === 401 || response.status === 403;
      const invalidPathError = isInvalidGatewayPathError(errorBody);

      return {
        status: 'error',
        detail: `Gateway returned HTTP ${response.status}: ${errorBody.substring(0, 100)}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: !authError && !invalidPathError,
        httpStatus: response.status,
        remediation: authError
          ? 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token'
          : invalidPathError
            ? 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.'
            : `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${response.status})`,
      };
    }

    // Successful response
    const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
      ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
      : undefined;
    return {
      status: 'ok',
      detail: `Gateway is responsive (${responseTime}ms)`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      ...(warning ? { warning } : {}),
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Network errors, timeouts, etc.
    const isTimeout = errorMessage.includes('timeout') || errorMessage.includes('Timeout');
    const isNetwork = errorMessage.includes('fetch') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('ENOTFOUND');

    return {
      status: 'error',
      detail: `Gateway is unreachable: ${errorMessage}`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: false,
      remediation: isTimeout
        ? 'Gateway is slow or not responding. Check gateway health and network connectivity'
        : isNetwork
          ? 'Cannot reach gateway endpoint. Verify the URL is reachable and check network/firewall rules'
          : 'Unexpected error connecting to gateway. Check logs for details',
    };
  }
}

/**
 * Test LLM gateway responsiveness
 *
 * @returns Gateway test result with status and diagnostics
 */
export async function testGatewayConnectivity(options: GatewayTestOptions = {}): Promise<GatewayTestResult> {
  const startTime = performance.now();
  const timestamp = new Date().toISOString();

  // Check configuration
  const gatewayUrl = process.env.LLM_GATEWAY_URL;
  const apiKey = resolveGatewayApiKey().value;

  if (!gatewayUrl) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_URL is not configured',
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set the LLM_GATEWAY_URL environment variable to your gateway endpoint (e.g., https://llmgateway.local.xyz/v1/responses)',
    };
  }

  if (!apiKey) {
    return {
      status: 'error',
      detail: 'LLM_GATEWAY_API_KEY is not configured',
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_API_KEY or provide a readable llm_gateway_api_key file in the configured Kaseki secrets directory',
    };
  }

  // Validate URL format
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(gatewayUrl);
    if (!parsedUrl.protocol.startsWith('http')) {
      throw new Error('URL must use HTTP or HTTPS');
    }
  } catch {
    return {
      status: 'error',
      detail: `Gateway URL is invalid: ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Ensure LLM_GATEWAY_URL is a valid HTTP/HTTPS URL',
    };
  }

  if (!isResponsesEndpoint(parsedUrl)) {
    return {
      status: 'error',
      detail: `Gateway URL must point to a versioned OpenAI API endpoint (/v1, /v2, etc.): ${gatewayUrl}`,
      gatewayUrl,
      responseTime: 0,
      timestamp,
      authenticationValidated: false,
      remediation: 'Set LLM_GATEWAY_URL to a base API endpoint such as https://gateway.example/v1. Pi CLI will automatically append /responses for the OpenAI Responses API. Examples: https://api.openai.com/v1, https://llmgateway.local.xyz/v1',
    };
  }

  // Make test request to the appropriate Stage 1 probe endpoint. Standard
  // OpenAI-compatible gateways can use /models; Cloudflare /compat gateways must
  // preserve the scoped /v1/{account_id}/{gateway_id}/compat path and probe chat completions.
  const stage1Probe = buildStage1ProbeRequest(gatewayUrl);

  try {
    const fetchStartTime = performance.now();
    const response = await fetchWithTimeout(stage1Probe.endpoint, stage1Probe.init, GATEWAY_MODELS_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);

    if (!response.ok) {
      const errorBody = await response.text();
      const authError = response.status === 401 || response.status === 403;
      const invalidPathError = isInvalidGatewayPathError(errorBody);

      return {
        status: 'error',
        detail: `Gateway returned HTTP ${response.status}: ${errorBody.substring(0, 100)}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: !authError && !invalidPathError,
        httpStatus: response.status,
        remediation: authError
          ? 'Authentication failed. Check that LLM_GATEWAY_API_KEY is valid, or that the llm_gateway_api_key file in the configured Kaseki secrets directory contains the expected token'
          : invalidPathError
            ? 'Gateway request path is invalid. For Cloudflare /compat gateways, preserve the scoped /v1/{account_id}/{gateway_id}/compat path and do not reduce it to /v1/models.'
            : `Gateway returned an error. Verify the gateway is healthy and the URL is correct (${response.status})`,
      };
    }

    if (shouldRunGatewayResponseSmoke(options)) {
      const smokeResult = await testGatewayResponseSmoke(gatewayUrl, apiKey, timestamp, startTime);
      if (smokeResult.status === 'error') return smokeResult;

      const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
        ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
        : undefined;
      return {
        ...smokeResult,
        detail: `Gateway is responsive and returned usable Responses API content (${smokeResult.responseTime}ms)`,
        warning,
      };
    }

    // Successful response
    const warning = responseTime >= GATEWAY_LATENCY_WARNING_MS
      ? `Gateway responded slowly (${responseTime}ms; warning threshold ${GATEWAY_LATENCY_WARNING_MS}ms).`
      : undefined;
    return {
      status: 'ok',
      detail: `Gateway is responsive (${responseTime}ms)`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      responseSmokeValidated: false,
      ...(warning ? { warning } : {}),
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Network errors, timeouts, etc.
    const isTimeout = errorMessage.includes('timeout') || errorMessage.includes('Timeout');
    const isNetwork = errorMessage.includes('fetch') || errorMessage.includes('ECONNREFUSED') || errorMessage.includes('ENOTFOUND');

    return {
      status: 'error',
      detail: `Gateway is unreachable: ${errorMessage}`,
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: false,
      remediation: isTimeout
        ? 'Gateway is slow or not responding. Check gateway health and network connectivity'
        : isNetwork
          ? 'Cannot reach gateway endpoint. Verify the URL is reachable and check network/firewall rules'
          : 'Unexpected error connecting to gateway. Check logs for details',
    };
  }
}

/**
 * Stage 2: Full response validation test
 * Tests model inference via /responses endpoint with the resolved gateway model
 * CONSUMES inference tokens - only call in production or when explicitly requested
 *
 * @param gatewayUrl Base gateway URL (e.g., https://llmgateway.local.xyz/v1)
 * @param apiKey LLM gateway API key
 * @param timestamp ISO 8601 timestamp for the test
 * @param startTime Performance.now() from test start
 * @returns ResponseSmokeTestResult with inference details
 */
export async function testGatewayResponseSmoke_Stage2(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<ResponseSmokeTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, false);
}

async function testGatewayResponseSmokeFull(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
  legacyShape: boolean,
): Promise<ResponseSmokeTestResult & GatewayTestResult> {
  const checks: ResponseSmokeSubcheck[] = [];

  // For Cloudflare gateways, skip full smoke testing (Cloudflare only supports Chat Completions, not Responses API)
  // The health check to /models endpoint already validated connectivity and authentication
  if (isCloudflareGateway(gatewayUrl)) {
    const responseTime = performance.now() - startTime;
    checks.push({
      name: 'cloudflare-compat-note',
      status: 'ok',
      detail: 'Cloudflare gateway detected. Full response smoke test skipped (Cloudflare only supports Chat Completions). Stage 1 uses the scoped /compat/chat/completions probe.',
      responseTime,
    });
    return {
      status: 'ok',
      detail: 'Cloudflare gateway connectivity verified (health check passed via scoped /compat probe, full Responses smoke test not applicable)',
      gatewayUrl,
      responseTime,
      timestamp,
      authenticationValidated: true,
      responseSmokeValidated: true, // Mark as validated since we did the health check
      checks,
    };
  }

  const jsonCheck = await runGatewayResponseJsonCheck(
    gatewayUrl,
    apiKey,
    timestamp,
    startTime,
    GATEWAY_RESPONSE_SMOKE_PROMPT,
    'json-response',
    legacyShape,
  );
  checks.push(jsonCheck.check);
  if (jsonCheck.result.status === 'error') {
    return { ...jsonCheck.result, checks };
  }

  const streamCheck = await runGatewayResponseStreamCheck(gatewayUrl, apiKey, timestamp, startTime);
  checks.push(streamCheck.check);
  if (streamCheck.result.status === 'error') {
    return { ...streamCheck.result, checks };
  }

  const largeCheck = await runGatewayResponseJsonCheck(
    gatewayUrl,
    apiKey,
    timestamp,
    startTime,
    GATEWAY_RESPONSE_LARGE_SMOKE_PROMPT,
    'large-prompt-response',
    legacyShape,
  );
  checks.push(largeCheck.check);
  if (largeCheck.result.status === 'error') {
    return { ...largeCheck.result, streamSmokeValidated: true, checks };
  }

  return {
    ...largeCheck.result,
    status: 'ok',
    detail: `Gateway Responses API smoke checks passed (${checks.length} checks)`,
    streamSmokeValidated: true,
    largePromptSmokeValidated: true,
    responseSmokeValidated: true,
    checks,
  };
}

async function runGatewayResponseJsonCheck(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
  prompt: string,
  checkName: 'json-response' | 'large-prompt-response',
  legacyShape: boolean,
): Promise<{ result: ResponseSmokeTestResult & GatewayTestResult; check: ResponseSmokeSubcheck }> {
  const responseEndpoint = buildResponsesEndpoint(gatewayUrl);
  const fetchStartTime = performance.now();
  try {
    const response = await fetchWithTimeout(responseEndpoint, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: resolveGatewayModel(),
        input: prompt,
        max_output_tokens: GATEWAY_RESPONSE_SMOKE_MAX_OUTPUT_TOKENS,
      }),
    }, GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);
    const bodyText = await response.text();
    if (!response.ok) {
      const authError = response.status === 401 || response.status === 403;
      return {
        result: {
          status: 'error',
          detail: `Gateway ${checkName} smoke test returned HTTP ${response.status}: ${bodyText.substring(0, 160)}`,
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: !authError,
          responseSmokeValidated: false,
          httpStatus: response.status,
          remediation: authError
            ? 'Authentication failed for the Responses API smoke test. Check that LLM_GATEWAY_API_KEY is valid for response generation.'
            : 'Gateway /responses path is unhealthy or incompatible. Verify the gateway supports OpenAI Responses API requests with the resolved gateway model (default dynamic/kaseki-agent).',
        },
        check: { name: checkName, status: 'error', detail: `HTTP ${response.status}`, responseTime },
      };
    }

    let body: unknown;
    try {
      body = JSON.parse(bodyText);
    } catch {
      return {
        result: {
          status: 'error',
          detail: `Gateway ${checkName} smoke test returned non-JSON content: ${bodyText.substring(0, 160)}`,
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: true,
          responseSmokeValidated: false,
          remediation: 'Gateway /responses should return OpenAI Responses-compatible JSON for dynamic/kaseki-agent by default, or the resolved gateway model.',
        },
        check: { name: checkName, status: 'error', detail: 'non-JSON response body', responseTime },
      };
    }

    const text = extractResponseText(body);
    const outputTokens = extractOutputTokens(body);
    const responseId = typeof (body as any)?.id === 'string' ? (body as any).id : undefined;
    if (!text.trim()) {
      const detailParts = [
        'Gateway Responses API smoke test returned no assistant text.',
        responseId ? `response_id=${responseId}` : '',
        outputTokens !== undefined ? `output_tokens=${outputTokens}` : '',
      ].filter(Boolean);
      return {
        result: {
          status: 'error',
          detail: detailParts.join(' '),
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: true,
          responseSmokeValidated: false,
          responseId,
          outputTokens,
          remediation: 'Gateway accepted the resolved gateway model for routing but returned an empty assistant response. Keep dynamic/kaseki-agent enabled by default, or set KASEKI_MODEL/LLM_GATEWAY_MODEL to a supported model; fix the Responses API adapter to surface routed model output as output_text, response.output_text.delta, or assistant message content.',
        },
        check: { name: checkName, status: 'error', detail: detailParts.join(' '), responseTime, responseId, outputTokens },
      };
    }

    return {
      result: {
        status: 'ok',
        detail: `${checkName} generated valid response (${responseTime}ms)`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: true,
        responseSmokeValidated: legacyShape ? true : undefined,
        responseId,
        outputTokens,
        largePromptSmokeValidated: checkName === 'large-prompt-response' ? true : undefined,
      },
      check: { name: checkName, status: 'ok', detail: 'assistant text returned', responseTime, responseId, outputTokens },
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      result: {
        status: 'error',
        detail: `Gateway ${checkName} smoke test failed: ${errorMessage}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: false,
        responseSmokeValidated: false,
        remediation: 'Cannot complete a Responses API request with the resolved gateway model. Check gateway health, routing, and network access.',
      },
      check: { name: checkName, status: 'error', detail: errorMessage, responseTime },
    };
  }
}

async function runGatewayResponseStreamCheck(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<{ result: ResponseSmokeTestResult & GatewayTestResult; check: ResponseSmokeSubcheck }> {
  const responseEndpoint = buildResponsesEndpoint(gatewayUrl);
  const fetchStartTime = performance.now();
  try {
    const response = await fetchWithTimeout(responseEndpoint, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: 'text/event-stream',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: resolveGatewayModel(),
        input: GATEWAY_RESPONSE_SMOKE_PROMPT,
        max_output_tokens: GATEWAY_RESPONSE_SMOKE_MAX_OUTPUT_TOKENS,
        stream: true,
      }),
    }, GATEWAY_RESPONSE_SMOKE_TIMEOUT_MS);

    const responseTime = Math.round(performance.now() - fetchStartTime);
    const bodyText = await response.text();
    if (!response.ok) {
      const authError = response.status === 401 || response.status === 403;
      return {
        result: {
          status: 'error',
          detail: `Gateway streaming smoke test returned HTTP ${response.status}: ${bodyText.substring(0, 160)}`,
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: !authError,
          responseSmokeValidated: false,
          streamSmokeValidated: false,
          httpStatus: response.status,
          remediation: authError
            ? 'Authentication failed for the streaming Responses API smoke test. Check that LLM_GATEWAY_API_KEY is valid for response generation.'
            : 'Gateway streaming /responses path is unhealthy or incompatible. Verify it emits OpenAI Responses SSE events for stream=true.',
        },
        check: { name: 'streaming-response', status: 'error', detail: `HTTP ${response.status}`, responseTime },
      };
    }

    const parsed = parseResponsesSse(bodyText);
    if (!parsed.text.trim()) {
      const detailParts = [
        'Gateway streaming smoke test returned no assistant text deltas.',
        parsed.responseId ? `response_id=${parsed.responseId}` : '',
        parsed.outputTokens !== undefined ? `output_tokens=${parsed.outputTokens}` : '',
      ].filter(Boolean);
      return {
        result: {
          status: 'error',
          detail: detailParts.join(' '),
          gatewayUrl,
          responseTime,
          timestamp,
          authenticationValidated: true,
          responseSmokeValidated: false,
          streamSmokeValidated: false,
          responseId: parsed.responseId,
          outputTokens: parsed.outputTokens,
          remediation: 'Gateway accepted stream=true but produced no response.output_text.delta events and no final assistant text. Fix the Responses API streaming adapter before running Kaseki agent traffic through the resolved gateway model.',
        },
        check: {
          name: 'streaming-response',
          status: 'error',
          detail: detailParts.join(' '),
          responseTime,
          responseId: parsed.responseId,
          outputTokens: parsed.outputTokens,
        },
      };
    }

    return {
      result: {
        status: 'ok',
        detail: `streaming-response generated valid deltas (${responseTime}ms)`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: true,
        responseSmokeValidated: true,
        streamSmokeValidated: true,
        responseId: parsed.responseId,
        outputTokens: parsed.outputTokens,
      },
      check: {
        name: 'streaming-response',
        status: 'ok',
        detail: 'assistant text deltas returned',
        responseTime,
        responseId: parsed.responseId,
        outputTokens: parsed.outputTokens,
      },
    };
  } catch (error) {
    const responseTime = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      result: {
        status: 'error',
        detail: `Gateway streaming smoke test failed: ${errorMessage}`,
        gatewayUrl,
        responseTime,
        timestamp,
        authenticationValidated: false,
        responseSmokeValidated: false,
        streamSmokeValidated: false,
        remediation: 'Cannot complete a stream=true Responses API request with the resolved gateway model. Check gateway health, routing, and SSE adapter behavior.',
      },
      check: { name: 'streaming-response', status: 'error', detail: errorMessage, responseTime },
    };
  }
}

async function testGatewayResponseSmoke(
  gatewayUrl: string,
  apiKey: string,
  timestamp: string,
  startTime: number,
): Promise<GatewayTestResult> {
  return testGatewayResponseSmokeFull(gatewayUrl, apiKey, timestamp, startTime, true);
}

/**
 * Detect if a gateway URL is a Cloudflare endpoint (ends with /compat)
 * Exported for testing
 */
export function isCloudflareGateway(url: string): boolean {
  try {
    const normalized = url.endsWith('/') ? url.slice(0, -1) : url;
    return /\/compat$/.test(new URL(normalized).pathname);
  } catch {
    return false;
  }
}

interface Stage1ProbeRequest {
  endpoint: string;
  init: Record<string, unknown>;
}

function buildStage1ProbeRequest(baseUrl: string): Stage1ProbeRequest {
  const apiKey = resolveGatewayApiKey().value ?? '';

  if (isCloudflareGateway(baseUrl)) {
    return {
      endpoint: buildCloudflareInferenceEndpoint(baseUrl),
      init: {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: resolveGatewayModel(),
          messages: [{ role: 'user', content: CLOUDFLARE_STAGE1_PROBE_PROMPT }],
          max_tokens: 1,
          stream: false,
        }),
      },
    };
  }

  return {
    endpoint: buildModelsEndpoint(baseUrl),
    init: {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: 'application/json',
      },
    },
  };
}

function isInvalidGatewayPathError(errorBody: string): boolean {
  return /invalid request path/i.test(errorBody);
}

/**
 * Build the appropriate models endpoint for the gateway
 * Handles both base URLs (/v1) and full paths (/v1/responses or /v1/chat/completions)
 * Exported for testing
 */
export function buildModelsEndpoint(baseUrl: string): string {
  const url = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;

  // Match base version path: /v1, /v2, /v3, etc., optionally with /responses or other paths
  const versionMatch = url.match(/\/(v\d+)(?:\/|$)/);

  if (versionMatch) {
    // Extract the base URL up to and including the version (e.g., https://example.com/v1)
    const baseWithVersion = url.split(versionMatch[0])[0] + '/' + versionMatch[1];
    return `${baseWithVersion}/models`;
  }

  // Default to OpenAI-compatible path (shouldn't reach here if validation works)
  return `${url}/v1/models`;
}

/**
 * Build the appropriate responses/chat endpoint for the gateway
 * For Cloudflare endpoints (/compat), returns base URL without appending /responses
 * For standard gateways, appends /responses for OpenAI Responses API
 * Exported for testing
 */
export function buildResponsesEndpoint(baseUrl: string): string {
  const url = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;

  // For Cloudflare gateways, return base URL as-is (SDK will handle path appending)
  if (isCloudflareGateway(url)) {
    return url;
  }

  // For standard gateways, append /responses if not already present
  if (/\/responses$/.test(url)) return url;
  return `${url}/responses`;
}

/**
 * Build the chat completions endpoint for Cloudflare gateways
 * Cloudflare requires /chat/completions for inference, not /responses
 * Exported for testing
 */
export function buildCloudflareInferenceEndpoint(baseUrl: string): string {
  if (!isCloudflareGateway(baseUrl)) {
    throw new Error('buildCloudflareInferenceEndpoint should only be used for Cloudflare URLs');
  }
  const url = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
  return `${url}/chat/completions`;
}

function extractResponseText(value: unknown): string {
  if (!value || typeof value !== 'object') return '';
  const response = value as any;
  if (typeof response.output_text === 'string') return response.output_text;
  if (typeof response.text === 'string') return response.text;
  if (Array.isArray(response.output)) {
    return response.output.map((item: any) => {
      if (!item || typeof item !== 'object') return '';
      if (typeof item.text === 'string') return item.text;
      if (!Array.isArray(item.content)) return '';
      return item.content.map((part: any) => {
        if (!part || typeof part !== 'object') return '';
        if (typeof part.text === 'string') return part.text;
        if (typeof part.output_text === 'string') return part.output_text;
        return '';
      }).join('');
    }).join('');
  }
  return '';
}

function extractOutputTokens(value: unknown): number | undefined {
  const usage = (value as any)?.usage;
  if (!usage || typeof usage !== 'object') return undefined;
  for (const key of ['output_tokens', 'output', 'completion_tokens']) {
    if (typeof usage[key] === 'number' && Number.isFinite(usage[key])) return usage[key];
  }
  return undefined;
}

function parseResponsesSse(bodyText: string): { text: string; responseId?: string; outputTokens?: number } {
  let text = '';
  let responseId: string | undefined;
  let outputTokens: number | undefined;
  for (const line of bodyText.split(/\r?\n/)) {
    if (!line.startsWith('data:')) continue;
    const data = line.slice('data:'.length).trim();
    if (!data || data === '[DONE]') continue;
    let event: any;
    try {
      event = JSON.parse(data);
    } catch {
      continue;
    }
    if (typeof event?.delta === 'string') text += event.delta;
    if (!responseId && typeof event?.response?.id === 'string') responseId = event.response.id;
    if (!responseId && typeof event?.item?.id === 'string') responseId = event.item.id;
    if (event?.response) {
      text += extractResponseText(event.response);
      outputTokens = outputTokens ?? extractOutputTokens(event.response);
    }
  }
  return { text, responseId, outputTokens };
}

/**
 * Extract the structure of the first few events for diagnostics
 * Sanitized to avoid leaking sensitive data
 */
export function extractSampleEventStructure(stdout: string): any[] {
  const samples: any[] = [];
  for (const line of stdout.split(/\r?\n/).slice(0, 5)) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('{')) continue;
    try {
      const event = JSON.parse(trimmed);
      // Build a sanitized structure showing only field names and types
      const sanitized = sanitizeEventStructure(event);
      samples.push(sanitized);
    } catch {
      // Skip malformed lines
    }
  }
  return samples;
}

/**
 * Recursively sanitize event structure to show field names/types without sensitive content
 */
function sanitizeEventStructure(obj: any, depth = 0, maxDepth = 3): any {
  if (depth > maxDepth) return '...';
  if (obj === null || obj === undefined) return null;
  if (typeof obj !== 'object') return typeof obj;
  if (Array.isArray(obj)) return `[${obj.length} items]`;

  const result: Record<string, any> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      // Show type and length for strings
      result[key] = `string(${Math.min(value.length, 50)})`;
    } else if (typeof value === 'number') {
      result[key] = 'number';
    } else if (typeof value === 'boolean') {
      result[key] = 'boolean';
    } else if (value === null) {
      result[key] = 'null';
    } else if (Array.isArray(value)) {
      result[key] = `[${value.length} items]`;
    } else if (typeof value === 'object') {
      result[key] = sanitizeEventStructure(value, depth + 1, maxDepth);
    }
  }
  return result;
}

function countPiJsonEvents(stdout: string): number {
  return stdout
    .split(/\r?\n/)
    .filter((line) => line.trim().startsWith('{'))
    .length;
}

/**
 * Extract assistant text from Pi provider JSONL output
 * Supports multiple response formats:
 * - Legacy Pi formats: message.text, message.output_text, message.assistantMessage
 * - Chat Completions: choices[0].message.content, choices[0].delta.content
 * - Direct content: message.content (string or array)
 * - Response wrapper: message.response.content
 * - Cloudflare variants: direct string content field
 */
export function extractPiJsonAssistantText(stdout: string): string {
  let text = '';
  for (const line of stdout.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('{')) continue;
    let event: any;
    try {
      event = JSON.parse(trimmed);
    } catch {
      continue;
    }
    const message = event?.message;
    if (!message || message.role !== 'assistant') continue;

    // Legacy Pi formats
    if (typeof message.text === 'string') text += message.text;
    if (typeof message.output_text === 'string') text += message.output_text;
    if (typeof message.assistantMessage === 'string') text += message.assistantMessage;

    // Chat Completions API: standard format with choices
    if (Array.isArray(message.choices) && message.choices.length > 0) {
      const choice = message.choices[0];
      // Standard message format
      if (typeof choice?.message?.content === 'string') {
        text += choice.message.content;
      }
      // Streaming delta format
      if (typeof choice?.delta?.content === 'string') {
        text += choice.delta.content;
      }
    }

    // Direct delta field (streaming format without choices wrapper)
    if (typeof message.delta?.content === 'string') {
      text += message.delta.content;
    }

    // Direct content field (Cloudflare and other variants)
    if (typeof message.content === 'string') {
      text += message.content;
    }

    // Content as array of parts (Pi format)
    if (Array.isArray(message.content)) {
      for (const part of message.content) {
        if (typeof part?.text === 'string') text += part.text;
        if (typeof part?.output_text === 'string') text += part.output_text;
        // Support content objects with direct content field
        if (typeof part?.content === 'string') text += part.content;
      }
    }

    // Response wrapper (some gateway implementations)
    if (typeof message.response?.content === 'string') {
      text += message.response.content;
    }
  }
  return text;
}

/**
 * Analyze response structure to help diagnose text extraction failures
 * Returns details about what fields were found and which patterns might work
 */
export function analyzeResponseStructure(stdout: string): {
  eventCount: number;
  eventsByType: Record<string, number>;
  fieldsFound: string[];
  eventsWithText: number;
  suggestedPatterns: string[];
} {
  const eventsByType: Record<string, number> = {};
  const fieldsFound = new Set<string>();
  let eventsWithText = 0;
  let eventCount = 0;

  for (const line of stdout.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('{')) continue;
    let event: any;
    try {
      event = JSON.parse(trimmed);
    } catch {
      continue;
    }
    eventCount++;

    if (event.type) {
      eventsByType[event.type] = (eventsByType[event.type] || 0) + 1;
    }

    const message = event?.message;
    if (!message) continue;

    // Track which fields are present
    if (typeof message.text === 'string') {
      fieldsFound.add('message.text');
      if (message.text.trim()) eventsWithText++;
    }
    if (typeof message.output_text === 'string') {
      fieldsFound.add('message.output_text');
      if (message.output_text.trim()) eventsWithText++;
    }
    if (typeof message.assistantMessage === 'string') {
      fieldsFound.add('message.assistantMessage');
      if (message.assistantMessage.trim()) eventsWithText++;
    }
    if (typeof message.content === 'string') {
      fieldsFound.add('message.content (string)');
      if (message.content.trim()) eventsWithText++;
    }
    if (Array.isArray(message.choices)) {
      fieldsFound.add('message.choices[]');
      const choice = message.choices[0];
      if (choice?.message?.content) fieldsFound.add('message.choices[0].message.content');
      if (choice?.delta?.content) fieldsFound.add('message.choices[0].delta.content');
    }
    // Direct delta field (streaming format without choices wrapper)
    if (typeof message.delta?.content === 'string') {
      fieldsFound.add('message.delta.content');
      if (message.delta.content.trim()) eventsWithText++;
    }
    if (message.response?.content) {
      fieldsFound.add('message.response.content');
    }
    if (Array.isArray(message.content)) {
      fieldsFound.add('message.content (array)');
      for (const part of message.content) {
        if (part?.text) fieldsFound.add('message.content[].text');
        if (part?.output_text) fieldsFound.add('message.content[].output_text');
      }
    }
  }

  // Suggest patterns based on what was found
  const suggestedPatterns: string[] = [];
  if (fieldsFound.has('message.text')) suggestedPatterns.push('message.text (legacy Pi)');
  if (fieldsFound.has('message.output_text')) suggestedPatterns.push('message.output_text (legacy Pi)');
  if (fieldsFound.has('message.content (string)')) suggestedPatterns.push('message.content string (Cloudflare)');
  if (fieldsFound.has('message.choices[0].message.content')) suggestedPatterns.push('choices[0].message.content (Chat Completions)');
  if (fieldsFound.has('message.choices[0].delta.content')) suggestedPatterns.push('choices[0].delta.content (streaming)');
  if (fieldsFound.has('message.delta.content')) suggestedPatterns.push('message.delta.content (streaming direct)');
  if (fieldsFound.has('message.response.content')) suggestedPatterns.push('response.content (wrapped)');

  return {
    eventCount,
    eventsByType,
    fieldsFound: Array.from(fieldsFound),
    eventsWithText,
    suggestedPatterns,
  };
}

export function isResponsesEndpoint(url: URL): boolean {
  return GATEWAY_VALID_PATH_PATTERN.test(url.pathname);
}

/**
 * Fetch with timeout
 */
async function fetchWithTimeout(
  url: string,
  options: Record<string, unknown>,
  timeoutMs: number,
): Promise<Response> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

  try {
    return await fetch(url, {
      ...options,
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timeoutId);
  }
}

/**
 * Export test result for use in API routes
 */
export function formatGatewayTestResponse(result: GatewayTestResult): object {
  return {
    status: result.status,
    detail: result.detail,
    gatewayUrl: result.gatewayUrl,
    responseTime: result.responseTime,
    timestamp: result.timestamp,
    authenticationValidated: result.authenticationValidated,
    remediation: result.remediation,
    httpStatus: result.httpStatus,
    warning: result.warning,
    responseSmokeValidated: result.responseSmokeValidated,
    responseId: result.responseId,
    outputTokens: result.outputTokens,
    streamSmokeValidated: (result as ResponseSmokeTestResult).streamSmokeValidated,
    largePromptSmokeValidated: (result as ResponseSmokeTestResult).largePromptSmokeValidated,
    checks: (result as ResponseSmokeTestResult).checks,
  };
}
