import { RunScorecardSchema, type RunScorecard } from './types/run-scorecard';
import { sanitizeScorecardText } from './run-scorecard-markdown-sanitize';

const PHASE_ORDER: Array<keyof RunScorecard['phases']> = ['scouting', 'goal_setting', 'coding', 'validation', 'goal_check', 'run_evaluation'];
const DIMENSION_LABELS: Record<string, string> = { goal_quality: 'Goal quality', scouting_quality: 'Scouting quality', implementation_quality: 'Implementation quality', validation_quality: 'Validation quality', goal_attainment: 'Goal attainment', evaluation_quality: 'Evaluation quality' };
const PHASE_LABELS: Record<string, string> = { scouting: 'Scouting', goal_setting: 'Analysis / goal setting', coding: 'Coding', validation: 'Validation', goal_check: 'Goal check', run_evaluation: 'Run evaluation' };
const MAX_ITEMS = 3;
const cell = (value: unknown): string => sanitizeScorecardText(value).replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
const number = (value: number): string => Number.isInteger(value) ? String(value) : value.toFixed(1);
const tokens = (usage: RunScorecard['token_totals']): number => usage.input_tokens + usage.output_tokens + usage.cache_read_tokens + usage.cache_write_tokens;
const tokenSummary = (usage: RunScorecard['token_totals']): string => usage.unavailable || usage.completeness === 'unavailable' ? 'unavailable' : `${tokens(usage)} total (${usage.input_tokens} input, ${usage.output_tokens} output, ${usage.cache_read_tokens} cache read, ${usage.cache_write_tokens} cache write${usage.unknown_tokens ? `, ${usage.unknown_tokens} unknown` : ''})`;
const duration = (milliseconds: number | null): string => milliseconds === null ? 'unavailable' : `${number(milliseconds / 1000)}s`;
const metrics = (values: Record<string, string | number | boolean | null>): string => Object.entries(values).filter(([key]) => !/(?:prompt|secret|credential|raw|response|evidence|prose)/i.test(key)).sort(([a], [b]) => a.localeCompare(b)).slice(0, MAX_ITEMS).map(([key, value]) => `${key.replace(/_/g, ' ')}=${value ?? 'unavailable'}`).join(', ') || 'None';

export function formatRunScorecardMarkdown(input: unknown): string {
  const parsed = RunScorecardSchema.safeParse(input); if (!parsed.success) return '> **Scorecard unavailable:** `run-scorecard.json` is missing or malformed.';
  const card = parsed.data; const dimensions = [...card.dimensions].sort((a, b) => Object.keys(DIMENSION_LABELS).indexOf(a.id) - Object.keys(DIMENSION_LABELS).indexOf(b.id));
  const strengths = dimensions.filter(d => d.normalized_score >= 80).slice(0, MAX_ITEMS).map(d => `${DIMENSION_LABELS[d.id]} (${number(d.normalized_score)})`);
  const penalties = dimensions.filter(d => d.normalized_score < 80).sort((a, b) => a.normalized_score - b.normalized_score).slice(0, MAX_ITEMS).map(d => `${DIMENSION_LABELS[d.id]} (${number(d.normalized_score)})`);
  const warnings = [...card.warnings, ...dimensions.flatMap(d => d.warnings)].map(w => sanitizeScorecardText(w)).filter(Boolean).slice(0, MAX_ITEMS);
  const lines = [`- **Overall:** ${number(card.overall_score)}/100 (${card.grade})`, `- **Rubric:** ${cell(card.rubric_version)}`, `- **Evidence coverage:** ${card.evidence_coverage.available}/${card.evidence_coverage.required} (${number(card.evidence_coverage.ratio * 100)}%)`, '', '| Dimension | Weight | Score | Weighted points | Status |', '| --- | ---: | ---: | ---: | --- |', ...dimensions.map(d => `| ${cell(DIMENSION_LABELS[d.id])} | ${number(d.effective_weight * 100)}% | ${number(d.normalized_score)} | ${number(d.weighted_points)} | ${cell(d.status)} |`), '', `- **Elapsed:** ${card.timing_totals.completeness === 'complete' ? duration(card.timing_totals.wall_clock_ms) : 'unavailable'}`, `- **Tokens:** ${tokenSummary(card.token_totals)}`, `- **Strengths:** ${strengths.length ? strengths.join('; ') : 'None identified from bounded score data.'}`, `- **Penalties:** ${penalties.length ? penalties.join('; ') : 'None.'}`, `- **Warnings:** ${warnings.length ? warnings.join('; ') : 'None.'}`, '', '<details><summary>Per-phase breakdown</summary>', '', '| Phase | Outcome | Elapsed | Tokens | Metrics | Completeness | Confidence |', '| --- | --- | ---: | ---: | --- | --- | ---: |', ...PHASE_ORDER.map(id => { const phase = card.phases[id]; return `| ${PHASE_LABELS[id]} | ${cell(phase.outcome)} | ${duration(phase.duration_ms)} | ${phase.token_usage.unavailable || phase.token_usage.completeness === 'unavailable' ? 'unavailable' : tokens(phase.token_usage)} | ${cell(metrics(phase.measurements))} | ${cell(phase.completeness)} | ${number(phase.confidence)}% |`; }), '', '</details>'];
  if (card.completeness !== 'complete' || card.evidence_coverage.ratio < 1 || card.token_totals.unavailable) lines.push('', `> **Provisional score:** some evidence is unavailable (${card.evidence_coverage.missing_critical.length ? card.evidence_coverage.missing_critical.map(cell).join(', ') : 'see coverage and phase completeness above'}).`);
  return lines.join('\n');
}
